//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.MediaPortalPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.MediaPortalPlugin.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares Player.
        /// </summary>
        internal static string AresTitle {
            get {
                return ResourceManager.GetString("AresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: Couldn&apos;t initialize BASS engine!.
        /// </summary>
        internal static string BassInitFail {
            get {
                return ResourceManager.GetString("BassInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected with client {0}.
        /// </summary>
        internal static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed connection with client..
        /// </summary>
        internal static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got length from client: .
        /// </summary>
        internal static string ClientLengthReceived {
            get {
                return ResourceManager.GetString("ClientLengthReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error listening for client: .
        /// </summary>
        internal static string ClientListenError {
            get {
                return ResourceManager.GetString("ClientListenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received command &apos;{0}&apos;.
        /// </summary>
        internal static string CommandReceived {
            get {
                return ResourceManager.GetString("CommandReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected with .
        /// </summary>
        internal static string ConnectedWith {
            get {
                return ResourceManager.GetString("ConnectedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Player..
        /// </summary>
        internal static string CouldNotFindPlayer {
            get {
                return ResourceManager.GetString("CouldNotFindPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start Player: {0}.
        /// </summary>
        internal static string CouldNotStartPlayer {
            get {
                return ResourceManager.GetString("CouldNotStartPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting on client request..
        /// </summary>
        internal static string DisconnectingClient {
            get {
                return ResourceManager.GetString("DisconnectingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements:.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key code: {0}.
        /// </summary>
        internal static string InvalidKeyCode {
            get {
                return ResourceManager.GetString("InvalidKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while listening for keys: .
        /// </summary>
        internal static string KeyListenError {
            get {
                return ResourceManager.GetString("KeyListenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received key ids: {0} {1}.
        /// </summary>
        internal static string KeyReceived {
            get {
                return ResourceManager.GetString("KeyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is too high..
        /// </summary>
        internal static string LengthTooHigh {
            get {
                return ResourceManager.GetString("LengthTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the project: {0}.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music:.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume:.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network State:.
        /// </summary>
        internal static string NetworkState {
            get {
                return ResourceManager.GetString("NetworkState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client didn&apos;t send ID.
        /// </summary>
        internal static string NoClientID {
            get {
                return ResourceManager.GetString("NoClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t send status info. Check network connection..
        /// </summary>
        internal static string NoStatusInfoError {
            get {
                return ResourceManager.GetString("NoStatusInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Volume:.
        /// </summary>
        internal static string OverallVolume {
            get {
                return ResourceManager.GetString("OverallVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received ping..
        /// </summary>
        internal static string PingReceived {
            get {
                return ResourceManager.GetString("PingReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ping received, assuming connection failure..
        /// </summary>
        internal static string PingTimeout {
            get {
                return ResourceManager.GetString("PingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Connection:.
        /// </summary>
        internal static string PlayerConnection {
            get {
                return ResourceManager.GetString("PlayerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string PlayerConnectionDown {
            get {
                return ResourceManager.GetString("PlayerConnectionDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established.
        /// </summary>
        internal static string PlayerConnectionEstablished {
            get {
                return ResourceManager.GetString("PlayerConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At element {0}: {1}.
        /// </summary>
        internal static string PlayError {
            get {
                return ResourceManager.GetString("PlayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server {0} found..
        /// </summary>
        internal static string ServerFound {
            get {
                return ResourceManager.GetString("ServerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the settings: {0}.
        /// </summary>
        internal static string SettingsStoreError {
            get {
                return ResourceManager.GetString("SettingsStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds Volume:.
        /// </summary>
        internal static string SoundsVolume {
            get {
                return ResourceManager.GetString("SoundsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting UDP broadcast.
        /// </summary>
        internal static string StartBroadcast {
            get {
                return ResourceManager.GetString("StartBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping UDP broadcast.
        /// </summary>
        internal static string StopBroadcast {
            get {
                return ResourceManager.GetString("StopBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing tags database: {0}.
        /// </summary>
        internal static string TagsDbError {
            get {
                return ResourceManager.GetString("TagsDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending UDP packet: .
        /// </summary>
        internal static string UDPError {
            get {
                return ResourceManager.GetString("UDPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending UDP packet &apos;{0}&apos;.
        /// </summary>
        internal static string UDPSending {
            get {
                return ResourceManager.GetString("UDPSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received volume command: type {0}, volume {1}.
        /// </summary>
        internal static string VolumeCommandReceived {
            get {
                return ResourceManager.GetString("VolumeCommandReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received out-of-range volume command.
        /// </summary>
        internal static string VolumeOutOfRange {
            get {
                return ResourceManager.GetString("VolumeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is wrong..
        /// </summary>
        internal static string WrongClientLength {
            get {
                return ResourceManager.GetString("WrongClientLength", resourceCulture);
            }
        }
    }
}
