#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ares.ModelInfo_Android.Resource", IsApplication=false)]

namespace Ares.ModelInfo_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020008
			public static int Ares = 2130837512;
			
			// aapt resource value: 0x7f020010
			public static int AwaitedElementNotFound = 2130837520;
			
			// aapt resource value: 0x7f02000c
			public static int CannotPlayURLS = 2130837516;
			
			// aapt resource value: 0x7f02000f
			public static int ConditionElementNotFound = 2130837519;
			
			// aapt resource value: 0x7f02000d
			public static int ErrorReadingPlaylist = 2130837517;
			
			// aapt resource value: 0x7f020001
			public static int ExpectedAttribute = 2130837505;
			
			// aapt resource value: 0x7f020003
			public static int ExpectedContent = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ExpectedDouble = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ExpectedElement = 2130837509;
			
			// aapt resource value: 0x7f020002
			public static int ExpectedInteger = 2130837506;
			
			// aapt resource value: 0x7f020006
			public static int FileNameMustBeSet = 2130837510;
			
			// aapt resource value: 0x7f020009
			public static int FileNotFound = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int ImportOverwrite = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int InvalidImportFile = 2130837515;
			
			// aapt resource value: 0x7f020007
			public static int InvalidVolume = 2130837511;
			
			// aapt resource value: 0x7f02000e
			public static int PlaylistNotFound = 2130837518;
			
			// aapt resource value: 0x7f020013
			public static int ReferencedElementNotFound = 2130837523;
			
			// aapt resource value: 0x7f020011
			public static int StartedElementNotFound = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int StoppedElementNotFound = 2130837522;
			
			// aapt resource value: 0x7f020014
			public static int TagNotFound = 2130837524;
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
