//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.CmdLinePlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.CmdLinePlayer.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares Command Line Player Version {0}.
        /// </summary>
        internal static string AresPlayer {
            get {
                return ResourceManager.GetString("AresPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never close Player..
        /// </summary>
        internal static string CmdLineOptionDaemon {
            get {
                return ResourceManager.GetString("CmdLineOptionDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this message and exit..
        /// </summary>
        internal static string CmdLineOptionHelp {
            get {
                return ResourceManager.GetString("CmdLineOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language for messages (en: English, de: German).
        /// </summary>
        internal static string CmdLineOptionLanguage {
            get {
                return ResourceManager.GetString("CmdLineOptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output message level: between 0 (Debug) and 3 (Error).
        /// </summary>
        internal static string CmdLineOptionMsgLevel {
            get {
                return ResourceManager.GetString("CmdLineOptionMsgLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Interactive: close on disconnect from Controller.
        /// </summary>
        internal static string CmdLineOptionNonInteractive {
            get {
                return ResourceManager.GetString("CmdLineOptionNonInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port to connect with special Controller (-1 to turn off).
        /// </summary>
        internal static string CmdLineOptionTcpPort {
            get {
                return ResourceManager.GetString("CmdLineOptionTcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port to send udp messages for Player detection.
        /// </summary>
        internal static string CmdLineOptionUdpPort {
            get {
                return ResourceManager.GetString("CmdLineOptionUdpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port to connect with Web Controller (-1 to turn off).
        /// </summary>
        internal static string CmdLineOptionWebTcpPort {
            get {
                return ResourceManager.GetString("CmdLineOptionWebTcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device (-1: default; 0: last used device; 1: first device; 2: second device; etc.).
        /// </summary>
        internal static string CmdLineOutputDevice {
            get {
                return ResourceManager.GetString("CmdLineOutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected with .
        /// </summary>
        internal static string ConnectedWith {
            get {
                return ResourceManager.GetString("ConnectedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: .
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access selected sound device! Fallback to default..
        /// </summary>
        internal static string DeviceInitError {
            get {
                return ResourceManager.GetString("DeviceInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing the project: {0}.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Message level given!.
        /// </summary>
        internal static string InvalidMsgLevel {
            get {
                return ResourceManager.GetString("InvalidMsgLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output device given!.
        /// </summary>
        internal static string InvalidOutputDevice {
            get {
                return ResourceManager.GetString("InvalidOutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TCP port given!.
        /// </summary>
        internal static string InvalidTcpPort {
            get {
                return ResourceManager.GetString("InvalidTcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UDP port given!.
        /// </summary>
        internal static string InvalidUdpPort {
            get {
                return ResourceManager.GetString("InvalidUdpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the project: {0}.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one project given!.
        /// </summary>
        internal static string MoreThanOneProject {
            get {
                return ResourceManager.GetString("MoreThanOneProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usable IP address found. Is the network available?.
        /// </summary>
        internal static string NoIpAddress {
            get {
                return ResourceManager.GetString("NoIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project Loaded.
        /// </summary>
        internal static string NoOpenedProject {
            get {
                return ResourceManager.GetString("NoOpenedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings found. Using default settings - you may wish to adapt {0}.
        /// </summary>
        internal static string NoSettings {
            get {
                return ResourceManager.GetString("NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t send status info. Check network connection..
        /// </summary>
        internal static string NoStatusInfoError {
            get {
                return ResourceManager.GetString("NoStatusInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit ....
        /// </summary>
        internal static string PressKeyToExit {
            get {
                return ResourceManager.GetString("PressKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing tags database:
        ///{0}.
        /// </summary>
        internal static string TagsDbError {
            get {
                return ResourceManager.GetString("TagsDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: .
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be saved. Reason:
        ///{0}.
        /// </summary>
        internal static string WriteSettingsError {
            get {
                return ResourceManager.GetString("WriteSettingsError", resourceCulture);
            }
        }
    }
}
