#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ares.Data.Android.Resource", IsApplication=false)]

namespace Ares.Data.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ExpectedAttribute = 2130837505;
			
			// aapt resource value: 0x7f020003
			public static int ExpectedContent = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ExpectedDouble = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ExpectedElement = 2130837509;
			
			// aapt resource value: 0x7f020002
			public static int ExpectedInteger = 2130837506;
			
			// aapt resource value: 0x7f020006
			public static int FileNameMustBeSet = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int InvalidVolume = 2130837511;
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
