//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.CommonGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.CommonGUI.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is used for elements {1} and {2}.
        /// </summary>
        internal static string DuplicateModeElementKey {
            get {
                return ResourceManager.GetString("DuplicateModeElementKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is used for modes {1} and {2}.
        /// </summary>
        internal static string DuplicateModeKey {
            get {
                return ResourceManager.GetString("DuplicateModeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key is reserved for global control.
        /// </summary>
        internal static string KeyGloballyReserved {
            get {
                return ResourceManager.GetString("KeyGloballyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key is already used to select the mode &quot;{0}&quot;.
        /// </summary>
        internal static string KeyUsedByMode {
            get {
                return ResourceManager.GetString("KeyUsedByMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key is already used to start &quot;{0}&quot;.
        /// </summary>
        internal static string KeyUsedByModeElement {
            get {
                return ResourceManager.GetString("KeyUsedByModeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is reserved for global control.
        /// </summary>
        internal static string ModeElementKeyGloballyReserved {
            get {
                return ResourceManager.GetString("ModeElementKeyGloballyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is used for element {1} and mode {2}.
        /// </summary>
        internal static string ModeElementKeyUsedByMode {
            get {
                return ResourceManager.GetString("ModeElementKeyUsedByMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key defined for element {0}.
        /// </summary>
        internal static string ModeElementNoKey {
            get {
                return ResourceManager.GetString("ModeElementNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is reserved for global control.
        /// </summary>
        internal static string ModeKeyGloballyReserved {
            get {
                return ResourceManager.GetString("ModeKeyGloballyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key defined for mode {0}.
        /// </summary>
        internal static string ModeNoKey {
            get {
                return ResourceManager.GetString("ModeNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a directory for the settings..
        /// </summary>
        internal static string NeedDirectory {
            get {
                return ResourceManager.GetString("NeedDirectory", resourceCulture);
            }
        }
    }
}
