//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.Online {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.Online.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve version history. Reason:
        ///{0}.
        /// </summary>
        internal static string ChangeLogError {
            get {
                return ResourceManager.GetString("ChangeLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en/ChangeLog.txt.
        /// </summary>
        internal static string ChangeLogFile {
            get {
                return ResourceManager.GetString("ChangeLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares must be closed for the update. Close Ares now?.
        /// </summary>
        internal static string CloseAres {
            get {
                return ResourceManager.GetString("CloseAres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open download web page. Reason:
        ///{0}.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving version history ....
        /// </summary>
        internal static string GettingChangeLog {
            get {
                return ResourceManager.GetString("GettingChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the newest version of Ares..
        /// </summary>
        internal static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open help web page. Reason:
        ///{0}.
        /// </summary>
        internal static string OpenHelpError {
            get {
                return ResourceManager.GetString("OpenHelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open web page. Reason:
        ///{0}.
        /// </summary>
        internal static string OpenHomepageError {
            get {
                return ResourceManager.GetString("OpenHomepageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for news ....
        /// </summary>
        internal static string SearchingNews {
            get {
                return ResourceManager.GetString("SearchingNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for new version ....
        /// </summary>
        internal static string SearchingVersion {
            get {
                return ResourceManager.GetString("SearchingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown OS. Please download Setup manually..
        /// </summary>
        internal static string UnknownOS {
            get {
                return ResourceManager.GetString("UnknownOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve current version. Reason:
        ///{0}.
        /// </summary>
        internal static string VersionError {
            get {
                return ResourceManager.GetString("VersionError", resourceCulture);
            }
        }
    }
}
