#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ares.Players_Android.Resource", IsApplication=false)]

namespace Ares.Players_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int Ares = 2130837505;
			
			// aapt resource value: 0x7f020009
			public static int AwaitedElementNotFound = 2130837513;
			
			// aapt resource value: 0x7f020032
			public static int BassAacLoadFail = 2130837554;
			
			// aapt resource value: 0x7f020033
			public static int BassDeviceAlready = 2130837555;
			
			// aapt resource value: 0x7f020034
			public static int BassDeviceDriver = 2130837556;
			
			// aapt resource value: 0x7f020035
			public static int BassDeviceFormat = 2130837557;
			
			// aapt resource value: 0x7f020036
			public static int BassDeviceInfo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public static int BassDeviceInvalid = 2130837559;
			
			// aapt resource value: 0x7f020038
			public static int BassFlacLoadFail = 2130837560;
			
			// aapt resource value: 0x7f020039
			public static int BassFxLoadFail = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public static int BassInitFail = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public static int BassLoadFail = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public static int BassNo3D = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public static int BassNoMem = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public static int BassOpusLoadFail = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public static int BassUnknown = 2130837567;
			
			// aapt resource value: 0x7f020010
			public static int BufLostError = 2130837520;
			
			// aapt resource value: 0x7f020005
			public static int CannotPlayURLS = 2130837509;
			
			// aapt resource value: 0x7f02004a
			public static int ClientConnected = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public static int ClientDisconnected = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public static int ClientLengthReceived = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public static int ClientListenError = 2130837581;
			
			// aapt resource value: 0x7f020011
			public static int CodecError = 2130837521;
			
			// aapt resource value: 0x7f02004e
			public static int CommandReceived = 2130837582;
			
			// aapt resource value: 0x7f020008
			public static int ConditionElementNotFound = 2130837512;
			
			// aapt resource value: 0x7f020012
			public static int CreateError = 2130837522;
			
			// aapt resource value: 0x7f020044
			public static int Default = 2130837572;
			
			// aapt resource value: 0x7f020040
			public static int DeviceDisabled = 2130837568;
			
			// aapt resource value: 0x7f020041
			public static int DeviceEnabled = 2130837569;
			
			// aapt resource value: 0x7f020013
			public static int DeviceError = 2130837523;
			
			// aapt resource value: 0x7f02004f
			public static int DisconnectingClient = 2130837583;
			
			// aapt resource value: 0x7f020014
			public static int DriverError = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int DxError = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int EndedError = 2130837526;
			
			// aapt resource value: 0x7f020006
			public static int ErrorReadingPlaylist = 2130837510;
			
			// aapt resource value: 0x7f02000e
			public static int ExpectedAttribute = 2130837518;
			
			// aapt resource value: 0x7f020045
			public static int ExpectedContent = 2130837573;
			
			// aapt resource value: 0x7f020046
			public static int ExpectedDouble = 2130837574;
			
			// aapt resource value: 0x7f020047
			public static int ExpectedElement = 2130837575;
			
			// aapt resource value: 0x7f02000f
			public static int ExpectedInteger = 2130837519;
			
			// aapt resource value: 0x7f020048
			public static int FileNameMustBeSet = 2130837576;
			
			// aapt resource value: 0x7f020002
			public static int FileNotFound = 2130837506;
			
			// aapt resource value: 0x7f020018
			public static int FileOpenError = 2130837528;
			
			// aapt resource value: 0x7f02002b
			public static int FilePlayingError = 2130837547;
			
			// aapt resource value: 0x7f020017
			public static int FileformError = 2130837527;
			
			// aapt resource value: 0x7f020019
			public static int FormatError = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int FreqError = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int HandleError = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int IllParamError = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int IllTypeError = 2130837533;
			
			// aapt resource value: 0x7f020003
			public static int ImportOverwrite = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int InvalidImportFile = 2130837508;
			
			// aapt resource value: 0x7f020050
			public static int InvalidKeyCode = 2130837584;
			
			// aapt resource value: 0x7f020049
			public static int InvalidVolume = 2130837577;
			
			// aapt resource value: 0x7f020051
			public static int KeyListenError = 2130837585;
			
			// aapt resource value: 0x7f020052
			public static int KeyReceived = 2130837586;
			
			// aapt resource value: 0x7f020053
			public static int LengthTooHigh = 2130837587;
			
			// aapt resource value: 0x7f02001e
			public static int MemError = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int No3DError = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int NoChanError = 2130837536;
			
			// aapt resource value: 0x7f020054
			public static int NoClientID = 2130837588;
			
			// aapt resource value: 0x7f020042
			public static int NoDevice = 2130837570;
			
			// aapt resource value: 0x7f020043
			public static int NoDeviceDriver = 2130837571;
			
			// aapt resource value: 0x7f020021
			public static int NoEaxError = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int NoFxError = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int NoHwError = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int NoPlayError = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int NotAudioError = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int NotFileError = 2130837542;
			
			// aapt resource value: 0x7f020055
			public static int PingReceived = 2130837589;
			
			// aapt resource value: 0x7f020056
			public static int PingTimeout = 2130837590;
			
			// aapt resource value: 0x7f020057
			public static int PlayError = 2130837591;
			
			// aapt resource value: 0x7f020027
			public static int PlayingError = 2130837543;
			
			// aapt resource value: 0x7f020007
			public static int PlaylistNotFound = 2130837511;
			
			// aapt resource value: 0x7f020028
			public static int PositionError = 2130837544;
			
			// aapt resource value: 0x7f02000c
			public static int ReferencedElementNotFound = 2130837516;
			
			// aapt resource value: 0x7f02002d
			public static int SetEffectError = 2130837549;
			
			// aapt resource value: 0x7f02002c
			public static int SetVolumeError = 2130837548;
			
			// aapt resource value: 0x7f020029
			public static int SpeakerError = 2130837545;
			
			// aapt resource value: 0x7f02002e
			public static int SpeakerNotAvailable = 2130837550;
			
			// aapt resource value: 0x7f020058
			public static int StartBroadcast = 2130837592;
			
			// aapt resource value: 0x7f02000a
			public static int StartedElementNotFound = 2130837514;
			
			// aapt resource value: 0x7f020059
			public static int StopBroadcast = 2130837593;
			
			// aapt resource value: 0x7f02000b
			public static int StoppedElementNotFound = 2130837515;
			
			// aapt resource value: 0x7f02002f
			public static int StreamingError = 2130837551;
			
			// aapt resource value: 0x7f02000d
			public static int TagNotFound = 2130837517;
			
			// aapt resource value: 0x7f020031
			public static int TaggedMusic = 2130837553;
			
			// aapt resource value: 0x7f020030
			public static int TagsDbError = 2130837552;
			
			// aapt resource value: 0x7f02005a
			public static int UDPError = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public static int UDPSending = 2130837595;
			
			// aapt resource value: 0x7f02002a
			public static int UnexpectedError = 2130837546;
			
			// aapt resource value: 0x7f02005c
			public static int VolumeCommandReceived = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public static int VolumeOutOfRange = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public static int WrongClientLength = 2130837598;
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
