//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.Player {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.Player.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ares ähnelt.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ares Player - {0} ähnelt.
        /// </summary>
        internal static string AresPlayer {
            get {
                return ResourceManager.GetString("AresPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device already initialized. ähnelt.
        /// </summary>
        internal static string BassDeviceAlready {
            get {
                return ResourceManager.GetString("BassDeviceAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device driver available. Are soundcard and speakers installed properly? Is the device in use by another application? ähnelt.
        /// </summary>
        internal static string BassDeviceDriver {
            get {
                return ResourceManager.GetString("BassDeviceDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound device doesn&apos;t support 44kHz sampling. ähnelt.
        /// </summary>
        internal static string BassDeviceFormat {
            get {
                return ResourceManager.GetString("BassDeviceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device: {0}, Driver: {1}, State: {2} ähnelt.
        /// </summary>
        internal static string BassDeviceInfo {
            get {
                return ResourceManager.GetString("BassDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid device. Are soundcard and speakers installed properly? ähnelt.
        /// </summary>
        internal static string BassDeviceInvalid {
            get {
                return ResourceManager.GetString("BassDeviceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load BASS Fx add-on library. Installation problem? ähnelt.
        /// </summary>
        internal static string BassFxLoadFail {
            get {
                return ResourceManager.GetString("BassFxLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal: Couldn&apos;t initialize BASS engine!
        ///Error message: {0}
        ///{1} ähnelt.
        /// </summary>
        internal static string BassInitFail {
            get {
                return ResourceManager.GetString("BassInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load BASS library. Installation problem? ähnelt.
        /// </summary>
        internal static string BassLoadFail {
            get {
                return ResourceManager.GetString("BassLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device has no 3D support. ähnelt.
        /// </summary>
        internal static string BassNo3D {
            get {
                return ResourceManager.GetString("BassNo3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is insufficient memory. ähnelt.
        /// </summary>
        internal static string BassNoMem {
            get {
                return ResourceManager.GetString("BassNoMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error. Are soundcard and speakers installed properly? ähnelt.
        /// </summary>
        internal static string BassUnknown {
            get {
                return ResourceManager.GetString("BassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected with  ähnelt.
        /// </summary>
        internal static string ConnectedWith {
            get {
                return ResourceManager.GetString("ConnectedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die disabled ähnelt.
        /// </summary>
        internal static string DeviceDisabled {
            get {
                return ResourceManager.GetString("DeviceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enabled ähnelt.
        /// </summary>
        internal static string DeviceEnabled {
            get {
                return ResourceManager.GetString("DeviceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable ähnelt.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start editor. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string EditorStartError {
            get {
                return ResourceManager.GetString("EditorStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable ähnelt.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to obtain lame.exe yourself and copy it into the Ares Player installation directory. ähnelt.
        /// </summary>
        internal static string GetLameYourself {
            get {
                return ResourceManager.GetString("GetLameYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://aresrpg.sourceforge.net/en/hilfe/Player.html ähnelt.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening the project: {0} ähnelt.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music List ähnelt.
        /// </summary>
        internal static string MusicList {
            get {
                return ResourceManager.GetString("MusicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music Tags ähnelt.
        /// </summary>
        internal static string MusicTags {
            get {
                return ResourceManager.GetString("MusicTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sound device found. ähnelt.
        /// </summary>
        internal static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sound device driver found. ähnelt.
        /// </summary>
        internal static string NoDeviceDriver {
            get {
                return ResourceManager.GetString("NoDeviceDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no elements in this mode ähnelt.
        /// </summary>
        internal static string NoElements {
            get {
                return ResourceManager.GetString("NoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Project Loaded ähnelt.
        /// </summary>
        internal static string NoOpenedProject {
            get {
                return ResourceManager.GetString("NoOpenedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This seems to be the first start of the player.
        ///You should adapt some settings first. ähnelt.
        /// </summary>
        internal static string NoSettings {
            get {
                return ResourceManager.GetString("NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t send status info. Check network connection. ähnelt.
        /// </summary>
        internal static string NoStatusInfoError {
            get {
                return ResourceManager.GetString("NoStatusInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no tags in this category ähnelt.
        /// </summary>
        internal static string NoTags {
            get {
                return ResourceManager.GetString("NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not connected ähnelt.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open a project ... ähnelt.
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project {0}? ähnelt.
        /// </summary>
        internal static string OpenProjectQuestion {
            get {
                return ResourceManager.GetString("OpenProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project file has changed. Stop playing and reload? ähnelt.
        /// </summary>
        internal static string ReloadProject {
            get {
                return ResourceManager.GetString("ReloadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Ares ... ähnelt.
        /// </summary>
        internal static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ... ähnelt.
        /// </summary>
        internal static string ShowMessages {
            get {
                return ResourceManager.GetString("ShowMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ... ähnelt.
        /// </summary>
        internal static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Editor ähnelt.
        /// </summary>
        internal static string StartEditor {
            get {
                return ResourceManager.GetString("StartEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error accessing tags database:
        ///{0} ähnelt.
        /// </summary>
        internal static string TagsDbError {
            get {
                return ResourceManager.GetString("TagsDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings could not be saved. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteSettingsError {
            get {
                return ResourceManager.GetString("WriteSettingsError", resourceCulture);
            }
        }
    }
}
