//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.Player {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.Player.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares Player - {0}.
        /// </summary>
        internal static string AresPlayer {
            get {
                return ResourceManager.GetString("AresPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected with .
        /// </summary>
        internal static string ConnectedWith {
            get {
                return ResourceManager.GetString("ConnectedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access selected sound device! Fallback to default..
        /// </summary>
        internal static string DeviceInitError {
            get {
                return ResourceManager.GetString("DeviceInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start editor. Reason:
        ///{0}.
        /// </summary>
        internal static string EditorStartError {
            get {
                return ResourceManager.GetString("EditorStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to obtain lame.exe yourself and copy it into the Ares Player installation directory..
        /// </summary>
        internal static string GetLameYourself {
            get {
                return ResourceManager.GetString("GetLameYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aresrpg.sourceforge.net/en/hilfe/Player.html.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing the project: {0}.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing ....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the project: {0}.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music List.
        /// </summary>
        internal static string MusicList {
            get {
                return ResourceManager.GetString("MusicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Tags.
        /// </summary>
        internal static string MusicTags {
            get {
                return ResourceManager.GetString("MusicTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no elements in this mode.
        /// </summary>
        internal static string NoElements {
            get {
                return ResourceManager.GetString("NoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project Loaded.
        /// </summary>
        internal static string NoOpenedProject {
            get {
                return ResourceManager.GetString("NoOpenedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This seems to be the first start of the player.
        ///You should adapt some settings first..
        /// </summary>
        internal static string NoSettings {
            get {
                return ResourceManager.GetString("NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t send status info. Check network connection..
        /// </summary>
        internal static string NoStatusInfoError {
            get {
                return ResourceManager.GetString("NoStatusInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tags in this category.
        /// </summary>
        internal static string NoTags {
            get {
                return ResourceManager.GetString("NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a project ....
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project {0}?.
        /// </summary>
        internal static string OpenProjectQuestion {
            get {
                return ResourceManager.GetString("OpenProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file has changed. Stop playing and reload?.
        /// </summary>
        internal static string ReloadProject {
            get {
                return ResourceManager.GetString("ReloadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Ares ....
        /// </summary>
        internal static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages ....
        /// </summary>
        internal static string ShowMessages {
            get {
                return ResourceManager.GetString("ShowMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings ....
        /// </summary>
        internal static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Editor.
        /// </summary>
        internal static string StartEditor {
            get {
                return ResourceManager.GetString("StartEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        internal static string Streaming {
            get {
                return ResourceManager.GetString("Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing tags database:
        ///{0}.
        /// </summary>
        internal static string TagsDbError {
            get {
                return ResourceManager.GetString("TagsDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be saved. Reason:
        ///{0}.
        /// </summary>
        internal static string WriteSettingsError {
            get {
                return ResourceManager.GetString("WriteSettingsError", resourceCulture);
            }
        }
    }
}
