//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.237
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.Players {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.Players.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected with client {0} ähnelt.
        /// </summary>
        internal static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closed connection with client. ähnelt.
        /// </summary>
        internal static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got length from client:  ähnelt.
        /// </summary>
        internal static string ClientLengthReceived {
            get {
                return ResourceManager.GetString("ClientLengthReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error listening for client:  ähnelt.
        /// </summary>
        internal static string ClientListenError {
            get {
                return ResourceManager.GetString("ClientListenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received command &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string CommandReceived {
            get {
                return ResourceManager.GetString("CommandReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting on client request. ähnelt.
        /// </summary>
        internal static string DisconnectingClient {
            get {
                return ResourceManager.GetString("DisconnectingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid key code: {0} ähnelt.
        /// </summary>
        internal static string InvalidKeyCode {
            get {
                return ResourceManager.GetString("InvalidKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while listening for keys:  ähnelt.
        /// </summary>
        internal static string KeyListenError {
            get {
                return ResourceManager.GetString("KeyListenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received key ids: {0} {1} ähnelt.
        /// </summary>
        internal static string KeyReceived {
            get {
                return ResourceManager.GetString("KeyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length is too high. ähnelt.
        /// </summary>
        internal static string LengthTooHigh {
            get {
                return ResourceManager.GetString("LengthTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client didn&apos;t send ID ähnelt.
        /// </summary>
        internal static string NoClientID {
            get {
                return ResourceManager.GetString("NoClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received ping. ähnelt.
        /// </summary>
        internal static string PingReceived {
            get {
                return ResourceManager.GetString("PingReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Ping received, assuming connection failure. ähnelt.
        /// </summary>
        internal static string PingTimeout {
            get {
                return ResourceManager.GetString("PingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At element {0}: {1} ähnelt.
        /// </summary>
        internal static string PlayError {
            get {
                return ResourceManager.GetString("PlayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting UDP broadcast ähnelt.
        /// </summary>
        internal static string StartBroadcast {
            get {
                return ResourceManager.GetString("StartBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping UDP broadcast ähnelt.
        /// </summary>
        internal static string StopBroadcast {
            get {
                return ResourceManager.GetString("StopBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error sending UDP packet:  ähnelt.
        /// </summary>
        internal static string UDPError {
            get {
                return ResourceManager.GetString("UDPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending UDP packet &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string UDPSending {
            get {
                return ResourceManager.GetString("UDPSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received volume command: type {0}, volume {1} ähnelt.
        /// </summary>
        internal static string VolumeCommandReceived {
            get {
                return ResourceManager.GetString("VolumeCommandReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received out-of-range volume command ähnelt.
        /// </summary>
        internal static string VolumeOutOfRange {
            get {
                return ResourceManager.GetString("VolumeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length is wrong. ähnelt.
        /// </summary>
        internal static string WrongClientLength {
            get {
                return ResourceManager.GetString("WrongClientLength", resourceCulture);
            }
        }
    }
}
