//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.Editor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.Editor.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ares ähnelt.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ares Editor - {0} ähnelt.
        /// </summary>
        internal static string AresEditorTitle {
            get {
                return ResourceManager.GetString("AresEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device already initialized. ähnelt.
        /// </summary>
        internal static string BassDeviceAlready {
            get {
                return ResourceManager.GetString("BassDeviceAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device driver available. Are soundcard and speakers installed properly? Is the device in use by another application? ähnelt.
        /// </summary>
        internal static string BassDeviceDriver {
            get {
                return ResourceManager.GetString("BassDeviceDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound device doesn&apos;t support 44kHz sampling. ähnelt.
        /// </summary>
        internal static string BassDeviceFormat {
            get {
                return ResourceManager.GetString("BassDeviceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device: {0}, Driver: {1}, State: {2} ähnelt.
        /// </summary>
        internal static string BassDeviceInfo {
            get {
                return ResourceManager.GetString("BassDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid device. Are soundcard and speakers installed properly? ähnelt.
        /// </summary>
        internal static string BassDeviceInvalid {
            get {
                return ResourceManager.GetString("BassDeviceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load BASS Fx add-on library. Installation problem? ähnelt.
        /// </summary>
        internal static string BassFxLoadFail {
            get {
                return ResourceManager.GetString("BassFxLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal: Couldn&apos;t initialize BASS engine!
        ///Error message: {0}
        ///{1} ähnelt.
        /// </summary>
        internal static string BassInitFail {
            get {
                return ResourceManager.GetString("BassInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load BASS library. Installation problem? ähnelt.
        /// </summary>
        internal static string BassLoadFail {
            get {
                return ResourceManager.GetString("BassLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device has no 3D support. ähnelt.
        /// </summary>
        internal static string BassNo3D {
            get {
                return ResourceManager.GetString("BassNo3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is insufficient memory. ähnelt.
        /// </summary>
        internal static string BassNoMem {
            get {
                return ResourceManager.GetString("BassNoMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error. Are soundcard and speakers installed properly? ähnelt.
        /// </summary>
        internal static string BassUnknown {
            get {
                return ResourceManager.GetString("BassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A parent directory can&apos;t be copied or moved into one of its child directories. ähnelt.
        /// </summary>
        internal static string CopyOrMoveParentIntoChild {
            get {
                return ResourceManager.GetString("CopyOrMoveParentIntoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error deleting files: {0} ähnelt.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die disabled ähnelt.
        /// </summary>
        internal static string DeviceDisabled {
            get {
                return ResourceManager.GetString("DeviceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enabled ähnelt.
        /// </summary>
        internal static string DeviceEnabled {
            get {
                return ResourceManager.GetString("DeviceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A second key press stops the element (it contains infinite repeats). ähnelt.
        /// </summary>
        internal static string ElementIsEndless {
            get {
                return ResourceManager.GetString("ElementIsEndless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A second key press starts the element a second time. ähnelt.
        /// </summary>
        internal static string ElementIsSingle {
            get {
                return ResourceManager.GetString("ElementIsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Explorer ähnelt.
        /// </summary>
        internal static string FileExplorerTitle {
            get {
                return ResourceManager.GetString("FileExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error at file: {0} ähnelt.
        /// </summary>
        internal static string FilePlayed {
            get {
                return ResourceManager.GetString("FilePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General
        ///=======
        ///Esc       - Stop all sounds and music
        ///Up        - Increase overall volume
        ///Down      - Decrease overall volume
        ///Page Up   - Increase sound volume
        ///Page Down - Decrease sound volume
        ///Ins       - Increase music volume
        ///Del       - Decrease music volume
        ///Right     - Next music title
        ///Left      - Previous music title ähnelt.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://aresrpg.sourceforge.net/en/hilfe/Editor.html ähnelt.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening the project: {0} ähnelt.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode &apos;{0}&apos;:  ähnelt.
        /// </summary>
        internal static string ModeIntro {
            get {
                return ResourceManager.GetString("ModeIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music ähnelt.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Background Sounds ähnelt.
        /// </summary>
        internal static string NewBackgroundSounds {
            get {
                return ResourceManager.GetString("NewBackgroundSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Parallel List ähnelt.
        /// </summary>
        internal static string NewParallelList {
            get {
                return ResourceManager.GetString("NewParallelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Playlist ähnelt.
        /// </summary>
        internal static string NewPlaylist {
            get {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Project ähnelt.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Random List ähnelt.
        /// </summary>
        internal static string NewRandomList {
            get {
                return ResourceManager.GetString("NewRandomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Scenario ähnelt.
        /// </summary>
        internal static string NewScenario {
            get {
                return ResourceManager.GetString("NewScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Sequential List ähnelt.
        /// </summary>
        internal static string NewSequentialList {
            get {
                return ResourceManager.GetString("NewSequentialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Sound Choice ähnelt.
        /// </summary>
        internal static string NewSoundChoice {
            get {
                return ResourceManager.GetString("NewSoundChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sound device found. ähnelt.
        /// </summary>
        internal static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sound device driver found. ähnelt.
        /// </summary>
        internal static string NoDeviceDriver {
            get {
                return ResourceManager.GetString("NoDeviceDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None of these elements can be dropped here. ähnelt.
        /// </summary>
        internal static string NoDroppableElements {
            get {
                return ResourceManager.GetString("NoDroppableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; is not currently used in the project. ähnelt.
        /// </summary>
        internal static string NoElementsFound {
            get {
                return ResourceManager.GetString("NoElementsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No file or folder found. ähnelt.
        /// </summary>
        internal static string NoFileOrFolderFound {
            get {
                return ResourceManager.GetString("NoFileOrFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No other file or folder found. ähnelt.
        /// </summary>
        internal static string NoFurtherFileOrFolderFound {
            get {
                return ResourceManager.GetString("NoFurtherFileOrFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No elements found in the file which could be imported here. ähnelt.
        /// </summary>
        internal static string NoImportableElements {
            get {
                return ResourceManager.GetString("NoImportableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;No Key&gt; ähnelt.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Project Opened ähnelt.
        /// </summary>
        internal static string NoOpenedProject {
            get {
                return ResourceManager.GetString("NoOpenedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No elements found in the file which could be pasted here. ähnelt.
        /// </summary>
        internal static string NoPasteableElements {
            get {
                return ResourceManager.GetString("NoPasteableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [No name] ähnelt.
        /// </summary>
        internal static string NoProjectName {
            get {
                return ResourceManager.GetString("NoProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This seems to be the first start of the editor.
        ///You should adapt some settings first. ähnelt.
        /// </summary>
        internal static string NoSettings {
            get {
                return ResourceManager.GetString("NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No audio file editor has been configured yet. Do you wish to configure one now? ähnelt.
        /// </summary>
        internal static string NoSoundFileEditor {
            get {
                return ResourceManager.GetString("NoSoundFileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open help web page. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string OpenHelpError {
            get {
                return ResourceManager.GetString("OpenHelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project {0}? ähnelt.
        /// </summary>
        internal static string OpenProjectQuestion {
            get {
                return ResourceManager.GetString("OpenProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start player. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string PlayerStartError {
            get {
                return ResourceManager.GetString("PlayerStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current project has unsaved changes. Shall it be saved now? ähnelt.
        /// </summary>
        internal static string ProjectChanged {
            get {
                return ResourceManager.GetString("ProjectChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files will be deleted permanently. Proceed? ähnelt.
        /// </summary>
        internal static string ReallyDelete {
            get {
                return ResourceManager.GetString("ReallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving the project: {0} ähnelt.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; is currently used here: ähnelt.
        /// </summary>
        internal static string SearchElementsTitle {
            get {
                return ResourceManager.GetString("SearchElementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set fading settings for all top-level elements. ähnelt.
        /// </summary>
        internal static string SetFadingForAll {
            get {
                return ResourceManager.GetString("SetFadingForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;&apos;t start editor. Error message: {0} ähnelt.
        /// </summary>
        internal static string SoundFileEditorStartFail {
            get {
                return ResourceManager.GetString("SoundFileEditorStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sounds ähnelt.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start of {0} ähnelt.
        /// </summary>
        internal static string TriggerEditorTitle {
            get {
                return ResourceManager.GetString("TriggerEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File list could not be written. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteFileListError {
            get {
                return ResourceManager.GetString("WriteFileListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keys could not be written. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteKeyListError {
            get {
                return ResourceManager.GetString("WriteKeyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings could not be saved. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteSettingsError {
            get {
                return ResourceManager.GetString("WriteSettingsError", resourceCulture);
            }
        }
    }
}
