//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ares.Editor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ares.Editor.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add category ähnelt.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adding files ... ähnelt.
        /// </summary>
        internal static string AddingFiles {
            get {
                return ResourceManager.GetString("AddingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ares ähnelt.
        /// </summary>
        internal static string Ares {
            get {
                return ResourceManager.GetString("Ares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ares Editor - {0} ähnelt.
        /// </summary>
        internal static string AresEditorTitle {
            get {
                return ResourceManager.GetString("AresEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die category ähnelt.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a category with this name. ähnelt.
        /// </summary>
        internal static string CategoryExists {
            get {
                return ResourceManager.GetString("CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copying ... ähnelt.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A parent directory can&apos;t be copied or moved into one of its child directories. ähnelt.
        /// </summary>
        internal static string CopyOrMoveParentIntoChild {
            get {
                return ResourceManager.GetString("CopyOrMoveParentIntoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please correct the errors first. See the tooltip of the error symbol for more information. ähnelt.
        /// </summary>
        internal static string CorrectErrorsFirst {
            get {
                return ResourceManager.GetString("CorrectErrorsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error deleting files: {0} ähnelt.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error downloading tags: {0} ähnelt.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading tags ... ähnelt.
        /// </summary>
        internal static string DownloadingTags {
            get {
                return ResourceManager.GetString("DownloadingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download of tags from {0} was successful. ähnelt.
        /// </summary>
        internal static string DownloadOperationSuccess {
            get {
                return ResourceManager.GetString("DownloadOperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A second key press stops the element (it contains infinite repeats). ähnelt.
        /// </summary>
        internal static string ElementIsEndless {
            get {
                return ResourceManager.GetString("ElementIsEndless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A second key press starts the element a second time. ähnelt.
        /// </summary>
        internal static string ElementIsSingle {
            get {
                return ResourceManager.GetString("ElementIsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error exporting the project: {0} ähnelt.
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting ... ähnelt.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;&apos;t start external player. Error message: {0} ähnelt.
        /// </summary>
        internal static string ExternalPlayerStartFail {
            get {
                return ResourceManager.GetString("ExternalPlayerStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting music ids ... ähnelt.
        /// </summary>
        internal static string ExtractingMusicIds {
            get {
                return ResourceManager.GetString("ExtractingMusicIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extracting tags ... ähnelt.
        /// </summary>
        internal static string ExtractingTags {
            get {
                return ResourceManager.GetString("ExtractingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Explorer ähnelt.
        /// </summary>
        internal static string FileExplorerTitle {
            get {
                return ResourceManager.GetString("FileExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during file operation: {0} ähnelt.
        /// </summary>
        internal static string FileOpError {
            get {
                return ResourceManager.GetString("FileOpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error at file: {0} ähnelt.
        /// </summary>
        internal static string FilePlayed {
            get {
                return ResourceManager.GetString("FilePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching files in DB ... ähnelt.
        /// </summary>
        internal static string FindingFilesInDB {
            get {
                return ResourceManager.GetString("FindingFilesInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://sourceforge.net/p/aresrpg/discussion/English/ ähnelt.
        /// </summary>
        internal static string ForumPage {
            get {
                return ResourceManager.GetString("ForumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General
        ///=======
        ///Esc       - Stop all sounds and music
        ///Up        - Increase overall volume
        ///Down      - Decrease overall volume
        ///Page Up   - Increase sound volume
        ///Page Down - Decrease sound volume
        ///Ins       - Increase music volume
        ///Del       - Decrease music volume
        ///Right     - Next music title
        ///Left      - Previous music title ähnelt.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting titles from ID3 tags ... ähnelt.
        /// </summary>
        internal static string GettingTitles {
            get {
                return ResourceManager.GetString("GettingTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://aresrpg.sourceforge.net/en/hilfe/Editor.html ähnelt.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error importing the project: {0} ähnelt.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing ... ähnelt.
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file doesn&apos;t contain an Ares project. If it contains a project element (e.g. a scenario), import the file at a mode in the Project Explorer. ähnelt.
        /// </summary>
        internal static string ImportNoProject {
            get {
                return ResourceManager.GetString("ImportNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The command still needs some data. Please select the necessary element(s). ähnelt.
        /// </summary>
        internal static string InsufficientCommandData {
            get {
                return ResourceManager.GetString("InsufficientCommandData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;not found&gt; ähnelt.
        /// </summary>
        internal static string InvalidModeElement {
            get {
                return ResourceManager.GetString("InvalidModeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language code must be two letters ähnelt.
        /// </summary>
        internal static string LangCodeWrong {
            get {
                return ResourceManager.GetString("LangCodeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a language with this name. ähnelt.
        /// </summary>
        internal static string LanguageExists {
            get {
                return ResourceManager.GetString("LanguageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a language with this code. Perhaps there&apos;s just no translation of its name into {0}. ähnelt.
        /// </summary>
        internal static string LanguageExists2 {
            get {
                return ResourceManager.GetString("LanguageExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name can&apos;t be empty ähnelt.
        /// </summary>
        internal static string LanguageMustHaveName {
            get {
                return ResourceManager.GetString("LanguageMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name in the language itself can&apos;t be empty ähnelt.
        /// </summary>
        internal static string LanguageMustHaveTranslation {
            get {
                return ResourceManager.GetString("LanguageMustHaveTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length: {0} ähnelt.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening the project: {0} ähnelt.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}/{1} ähnelt.
        /// </summary>
        internal static string ModeElementDisplay {
            get {
                return ResourceManager.GetString("ModeElementDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode &apos;{0}&apos;:  ähnelt.
        /// </summary>
        internal static string ModeIntro {
            get {
                return ResourceManager.GetString("ModeIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moving ... ähnelt.
        /// </summary>
        internal static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music ähnelt.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error getting music ids: {0} ähnelt.
        /// </summary>
        internal static string MusicIdExtractionError {
            get {
                return ResourceManager.GetString("MusicIdExtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ids were found for {0} of {1} files. ähnelt.
        /// </summary>
        internal static string MusicIdStats {
            get {
                return ResourceManager.GetString("MusicIdStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name in {0}: ähnelt.
        /// </summary>
        internal static string NameInLanguage {
            get {
                return ResourceManager.GetString("NameInLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Background Sounds ähnelt.
        /// </summary>
        internal static string NewBackgroundSounds {
            get {
                return ResourceManager.GetString("NewBackgroundSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the new category: ähnelt.
        /// </summary>
        internal static string NewCategoryName {
            get {
                return ResourceManager.GetString("NewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New name of the category: ähnelt.
        /// </summary>
        internal static string NewCategoryName2 {
            get {
                return ResourceManager.GetString("NewCategoryName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New name of the language: ähnelt.
        /// </summary>
        internal static string NewLanguageName {
            get {
                return ResourceManager.GetString("NewLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Macro ähnelt.
        /// </summary>
        internal static string NewMacro {
            get {
                return ResourceManager.GetString("NewMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Parallel List ähnelt.
        /// </summary>
        internal static string NewParallelList {
            get {
                return ResourceManager.GetString("NewParallelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Playlist ähnelt.
        /// </summary>
        internal static string NewPlaylist {
            get {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Project ähnelt.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Random List ähnelt.
        /// </summary>
        internal static string NewRandomList {
            get {
                return ResourceManager.GetString("NewRandomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Scenario ähnelt.
        /// </summary>
        internal static string NewScenario {
            get {
                return ResourceManager.GetString("NewScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Sequential List ähnelt.
        /// </summary>
        internal static string NewSequentialList {
            get {
                return ResourceManager.GetString("NewSequentialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Sound Choice ähnelt.
        /// </summary>
        internal static string NewSoundChoice {
            get {
                return ResourceManager.GetString("NewSoundChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New name of the tag: ähnelt.
        /// </summary>
        internal static string NewTagName {
            get {
                return ResourceManager.GetString("NewTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None of these elements can be dropped here. ähnelt.
        /// </summary>
        internal static string NoDroppableElements {
            get {
                return ResourceManager.GetString("NoDroppableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; is not currently used in the project. ähnelt.
        /// </summary>
        internal static string NoElementsFound {
            get {
                return ResourceManager.GetString("NoElementsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No file or folder found. ähnelt.
        /// </summary>
        internal static string NoFileOrFolderFound {
            get {
                return ResourceManager.GetString("NoFileOrFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No other file or folder found. ähnelt.
        /// </summary>
        internal static string NoFurtherFileOrFolderFound {
            get {
                return ResourceManager.GetString("NoFurtherFileOrFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No elements found in the file which could be imported here. ähnelt.
        /// </summary>
        internal static string NoImportableElements {
            get {
                return ResourceManager.GetString("NoImportableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;No Key&gt; ähnelt.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Project Opened ähnelt.
        /// </summary>
        internal static string NoOpenedProject {
            get {
                return ResourceManager.GetString("NoOpenedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No elements found in the file which could be pasted here. ähnelt.
        /// </summary>
        internal static string NoPasteableElements {
            get {
                return ResourceManager.GetString("NoPasteableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [No name] ähnelt.
        /// </summary>
        internal static string NoProjectName {
            get {
                return ResourceManager.GetString("NoProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This seems to be the first start of the editor.
        ///You should adapt some settings first. ähnelt.
        /// </summary>
        internal static string NoSettings {
            get {
                return ResourceManager.GetString("NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No audio file editor has been configured yet. Do you wish to configure one now? ähnelt.
        /// </summary>
        internal static string NoSoundFileEditor {
            get {
                return ResourceManager.GetString("NoSoundFileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No tags set for the file ähnelt.
        /// </summary>
        internal static string NoTags {
            get {
                return ResourceManager.GetString("NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No element selected ähnelt.
        /// </summary>
        internal static string NoTranslationsLabelText {
            get {
                return ResourceManager.GetString("NoTranslationsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Tags DB ähnelt.
        /// </summary>
        internal static string OnlineDB {
            get {
                return ResourceManager.GetString("OnlineDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To upload tags, a user name (e.g. an e-mail address) is required. Would you like to set it now? ähnelt.
        /// </summary>
        internal static string OnlineDbUserIdRequired {
            get {
                return ResourceManager.GetString("OnlineDbUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open help web page. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string OpenHelpError {
            get {
                return ResourceManager.GetString("OpenHelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file doesn&apos;t contain a valid Ares project. If it contains a project element (e.g. a szenario), import the file at a mode in the Project Explorer. ähnelt.
        /// </summary>
        internal static string OpenProjectError {
            get {
                return ResourceManager.GetString("OpenProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project {0}? ähnelt.
        /// </summary>
        internal static string OpenProjectQuestion {
            get {
                return ResourceManager.GetString("OpenProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start player. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string PlayerStartError {
            get {
                return ResourceManager.GetString("PlayerStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an element ähnelt.
        /// </summary>
        internal static string PleaseSelectElement {
            get {
                return ResourceManager.GetString("PleaseSelectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a tag ähnelt.
        /// </summary>
        internal static string PleaseSelectTag {
            get {
                return ResourceManager.GetString("PleaseSelectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current project has unsaved changes. Shall it be saved now? ähnelt.
        /// </summary>
        internal static string ProjectChanged {
            get {
                return ResourceManager.GetString("ProjectChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files will be deleted permanently. Proceed? ähnelt.
        /// </summary>
        internal static string ReallyDelete {
            get {
                return ResourceManager.GetString("ReallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting a category also deletes all its tags and it can&apos;t be undone. Are you sure? ähnelt.
        /// </summary>
        internal static string ReallyDeleteCategory {
            get {
                return ResourceManager.GetString("ReallyDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting a language will also delete all translations of tags or categories in that language, and it can&apos;t be undone. Are you sure? ähnelt.
        /// </summary>
        internal static string ReallyDeleteLanguage {
            get {
                return ResourceManager.GetString("ReallyDeleteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting a tag can&apos;t be undone. Are you sure? ähnelt.
        /// </summary>
        internal static string ReallyDeleteTag {
            get {
                return ResourceManager.GetString("ReallyDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting a translation can&apos;t be undone. Are you sure? ähnelt.
        /// </summary>
        internal static string ReallyDeleteTranslation {
            get {
                return ResourceManager.GetString("ReallyDeleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename category ähnelt.
        /// </summary>
        internal static string RenameCategory {
            get {
                return ResourceManager.GetString("RenameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename language ähnelt.
        /// </summary>
        internal static string RenameLanguage {
            get {
                return ResourceManager.GetString("RenameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename tag ähnelt.
        /// </summary>
        internal static string RenameTag {
            get {
                return ResourceManager.GetString("RenameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving the project: {0} ähnelt.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; is currently used here: ähnelt.
        /// </summary>
        internal static string SearchElementsTitle {
            get {
                return ResourceManager.GetString("SearchElementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set fading settings for all top-level elements. ähnelt.
        /// </summary>
        internal static string SetFadingForAll {
            get {
                return ResourceManager.GetString("SetFadingForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sharing tags ... ähnelt.
        /// </summary>
        internal static string SharingTags {
            get {
                return ResourceManager.GetString("SharingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;&apos;t start editor. Error message: {0} ähnelt.
        /// </summary>
        internal static string SoundFileEditorStartFail {
            get {
                return ResourceManager.GetString("SoundFileEditorStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sounds ähnelt.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tag ähnelt.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a tag with this name. ähnelt.
        /// </summary>
        internal static string TagExists {
            get {
                return ResourceManager.GetString("TagExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error extracting the tags: {0} ähnelt.
        /// </summary>
        internal static string TagExtractionError {
            get {
                return ResourceManager.GetString("TagExtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tag must have a category. ähnelt.
        /// </summary>
        internal static string TagMustHaveCategory {
            get {
                return ResourceManager.GetString("TagMustHaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tag must have a name. ähnelt.
        /// </summary>
        internal static string TagMustHaveName {
            get {
                return ResourceManager.GetString("TagMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags:  ähnelt.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags database has been cleaned up. Show log? ähnelt.
        /// </summary>
        internal static string TagsCleanedUp {
            get {
                return ResourceManager.GetString("TagsCleanedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error accessing tags database:
        ///{0} ähnelt.
        /// </summary>
        internal static string TagsDbError {
            get {
                return ResourceManager.GetString("TagsDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags were found for {0} of {1} files. ähnelt.
        /// </summary>
        internal static string TagsDownloadStats {
            get {
                return ResourceManager.GetString("TagsDownloadStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags for {0} files ähnelt.
        /// </summary>
        internal static string TagsForMultipleFiles {
            get {
                return ResourceManager.GetString("TagsForMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags for {0} ähnelt.
        /// </summary>
        internal static string TagsForSingleFile {
            get {
                return ResourceManager.GetString("TagsForSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TipsOfTheDay.xml ähnelt.
        /// </summary>
        internal static string TipsFile {
            get {
                return ResourceManager.GetString("TipsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translation of &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string TranslationBoxTitle {
            get {
                return ResourceManager.GetString("TranslationBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name can&apos;t be empty ähnelt.
        /// </summary>
        internal static string TranslationMustHaveName {
            get {
                return ResourceManager.GetString("TranslationMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translations for {0} &apos;{1}&apos;: ähnelt.
        /// </summary>
        internal static string TranslationsLabelText {
            get {
                return ResourceManager.GetString("TranslationsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start of {0} ähnelt.
        /// </summary>
        internal static string TriggerEditorTitle {
            get {
                return ResourceManager.GetString("TriggerEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error sharing tags: {0} ähnelt.
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload of tags to {0} was successful. ähnelt.
        /// </summary>
        internal static string UploadOperationSuccess {
            get {
                return ResourceManager.GetString("UploadOperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File list could not be written. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteFileListError {
            get {
                return ResourceManager.GetString("WriteFileListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keys could not be written. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteKeyListError {
            get {
                return ResourceManager.GetString("WriteKeyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings could not be saved. Reason:
        ///{0} ähnelt.
        /// </summary>
        internal static string WriteSettingsError {
            get {
                return ResourceManager.GetString("WriteSettingsError", resourceCulture);
            }
        }
    }
}
