#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ares.Player_Android.Resource", IsApplication=true)]

namespace Ares.Player_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Ares.Data.Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Data.Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.Data.Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.Data.Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.Data.Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Data.Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.Data.Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.Data.Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.ModelInfo_Android.Resource.String.Ares = global::Ares.Player_Android.Resource.String.Ares;
			global::Ares.ModelInfo_Android.Resource.String.AwaitedElementNotFound = global::Ares.Player_Android.Resource.String.AwaitedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.CannotPlayURLS = global::Ares.Player_Android.Resource.String.CannotPlayURLS;
			global::Ares.ModelInfo_Android.Resource.String.ConditionElementNotFound = global::Ares.Player_Android.Resource.String.ConditionElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.ErrorReadingPlaylist = global::Ares.Player_Android.Resource.String.ErrorReadingPlaylist;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.ModelInfo_Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.ModelInfo_Android.Resource.String.FileNotFound = global::Ares.Player_Android.Resource.String.FileNotFound;
			global::Ares.ModelInfo_Android.Resource.String.ImportOverwrite = global::Ares.Player_Android.Resource.String.ImportOverwrite;
			global::Ares.ModelInfo_Android.Resource.String.InvalidImportFile = global::Ares.Player_Android.Resource.String.InvalidImportFile;
			global::Ares.ModelInfo_Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.ModelInfo_Android.Resource.String.PlaylistNotFound = global::Ares.Player_Android.Resource.String.PlaylistNotFound;
			global::Ares.ModelInfo_Android.Resource.String.ReferencedElementNotFound = global::Ares.Player_Android.Resource.String.ReferencedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.StartedElementNotFound = global::Ares.Player_Android.Resource.String.StartedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.StoppedElementNotFound = global::Ares.Player_Android.Resource.String.StoppedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.TagNotFound = global::Ares.Player_Android.Resource.String.TagNotFound;
			global::Ares.ModelInfo_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.Players_Android.Resource.String.Ares = global::Ares.Player_Android.Resource.String.Ares;
			global::Ares.Players_Android.Resource.String.AwaitedElementNotFound = global::Ares.Player_Android.Resource.String.AwaitedElementNotFound;
			global::Ares.Players_Android.Resource.String.BassAacLoadFail = global::Ares.Player_Android.Resource.String.BassAacLoadFail;
			global::Ares.Players_Android.Resource.String.BassDeviceAlready = global::Ares.Player_Android.Resource.String.BassDeviceAlready;
			global::Ares.Players_Android.Resource.String.BassDeviceDriver = global::Ares.Player_Android.Resource.String.BassDeviceDriver;
			global::Ares.Players_Android.Resource.String.BassDeviceFormat = global::Ares.Player_Android.Resource.String.BassDeviceFormat;
			global::Ares.Players_Android.Resource.String.BassDeviceInfo = global::Ares.Player_Android.Resource.String.BassDeviceInfo;
			global::Ares.Players_Android.Resource.String.BassDeviceInvalid = global::Ares.Player_Android.Resource.String.BassDeviceInvalid;
			global::Ares.Players_Android.Resource.String.BassFlacLoadFail = global::Ares.Player_Android.Resource.String.BassFlacLoadFail;
			global::Ares.Players_Android.Resource.String.BassFxLoadFail = global::Ares.Player_Android.Resource.String.BassFxLoadFail;
			global::Ares.Players_Android.Resource.String.BassInitFail = global::Ares.Player_Android.Resource.String.BassInitFail;
			global::Ares.Players_Android.Resource.String.BassLoadFail = global::Ares.Player_Android.Resource.String.BassLoadFail;
			global::Ares.Players_Android.Resource.String.BassNo3D = global::Ares.Player_Android.Resource.String.BassNo3D;
			global::Ares.Players_Android.Resource.String.BassNoMem = global::Ares.Player_Android.Resource.String.BassNoMem;
			global::Ares.Players_Android.Resource.String.BassOpusLoadFail = global::Ares.Player_Android.Resource.String.BassOpusLoadFail;
			global::Ares.Players_Android.Resource.String.BassUnknown = global::Ares.Player_Android.Resource.String.BassUnknown;
			global::Ares.Players_Android.Resource.String.BufLostError = global::Ares.Player_Android.Resource.String.BufLostError;
			global::Ares.Players_Android.Resource.String.CannotPlayURLS = global::Ares.Player_Android.Resource.String.CannotPlayURLS;
			global::Ares.Players_Android.Resource.String.ClientConnected = global::Ares.Player_Android.Resource.String.ClientConnected;
			global::Ares.Players_Android.Resource.String.ClientDisconnected = global::Ares.Player_Android.Resource.String.ClientDisconnected;
			global::Ares.Players_Android.Resource.String.ClientLengthReceived = global::Ares.Player_Android.Resource.String.ClientLengthReceived;
			global::Ares.Players_Android.Resource.String.ClientListenError = global::Ares.Player_Android.Resource.String.ClientListenError;
			global::Ares.Players_Android.Resource.String.CodecError = global::Ares.Player_Android.Resource.String.CodecError;
			global::Ares.Players_Android.Resource.String.CommandReceived = global::Ares.Player_Android.Resource.String.CommandReceived;
			global::Ares.Players_Android.Resource.String.ConditionElementNotFound = global::Ares.Player_Android.Resource.String.ConditionElementNotFound;
			global::Ares.Players_Android.Resource.String.CreateError = global::Ares.Player_Android.Resource.String.CreateError;
			global::Ares.Players_Android.Resource.String.Default = global::Ares.Player_Android.Resource.String.Default;
			global::Ares.Players_Android.Resource.String.DeviceDisabled = global::Ares.Player_Android.Resource.String.DeviceDisabled;
			global::Ares.Players_Android.Resource.String.DeviceEnabled = global::Ares.Player_Android.Resource.String.DeviceEnabled;
			global::Ares.Players_Android.Resource.String.DeviceError = global::Ares.Player_Android.Resource.String.DeviceError;
			global::Ares.Players_Android.Resource.String.DisconnectingClient = global::Ares.Player_Android.Resource.String.DisconnectingClient;
			global::Ares.Players_Android.Resource.String.DriverError = global::Ares.Player_Android.Resource.String.DriverError;
			global::Ares.Players_Android.Resource.String.DxError = global::Ares.Player_Android.Resource.String.DxError;
			global::Ares.Players_Android.Resource.String.EndedError = global::Ares.Player_Android.Resource.String.EndedError;
			global::Ares.Players_Android.Resource.String.ErrorReadingPlaylist = global::Ares.Player_Android.Resource.String.ErrorReadingPlaylist;
			global::Ares.Players_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Players_Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.Players_Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.Players_Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.Players_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Players_Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.Players_Android.Resource.String.FileNotFound = global::Ares.Player_Android.Resource.String.FileNotFound;
			global::Ares.Players_Android.Resource.String.FileOpenError = global::Ares.Player_Android.Resource.String.FileOpenError;
			global::Ares.Players_Android.Resource.String.FilePlayingError = global::Ares.Player_Android.Resource.String.FilePlayingError;
			global::Ares.Players_Android.Resource.String.FileformError = global::Ares.Player_Android.Resource.String.FileformError;
			global::Ares.Players_Android.Resource.String.FormatError = global::Ares.Player_Android.Resource.String.FormatError;
			global::Ares.Players_Android.Resource.String.FreqError = global::Ares.Player_Android.Resource.String.FreqError;
			global::Ares.Players_Android.Resource.String.HandleError = global::Ares.Player_Android.Resource.String.HandleError;
			global::Ares.Players_Android.Resource.String.IllParamError = global::Ares.Player_Android.Resource.String.IllParamError;
			global::Ares.Players_Android.Resource.String.IllTypeError = global::Ares.Player_Android.Resource.String.IllTypeError;
			global::Ares.Players_Android.Resource.String.ImportOverwrite = global::Ares.Player_Android.Resource.String.ImportOverwrite;
			global::Ares.Players_Android.Resource.String.InvalidImportFile = global::Ares.Player_Android.Resource.String.InvalidImportFile;
			global::Ares.Players_Android.Resource.String.InvalidKeyCode = global::Ares.Player_Android.Resource.String.InvalidKeyCode;
			global::Ares.Players_Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.Players_Android.Resource.String.KeyListenError = global::Ares.Player_Android.Resource.String.KeyListenError;
			global::Ares.Players_Android.Resource.String.KeyReceived = global::Ares.Player_Android.Resource.String.KeyReceived;
			global::Ares.Players_Android.Resource.String.LengthTooHigh = global::Ares.Player_Android.Resource.String.LengthTooHigh;
			global::Ares.Players_Android.Resource.String.MemError = global::Ares.Player_Android.Resource.String.MemError;
			global::Ares.Players_Android.Resource.String.No3DError = global::Ares.Player_Android.Resource.String.No3DError;
			global::Ares.Players_Android.Resource.String.NoChanError = global::Ares.Player_Android.Resource.String.NoChanError;
			global::Ares.Players_Android.Resource.String.NoClientID = global::Ares.Player_Android.Resource.String.NoClientID;
			global::Ares.Players_Android.Resource.String.NoDevice = global::Ares.Player_Android.Resource.String.NoDevice;
			global::Ares.Players_Android.Resource.String.NoDeviceDriver = global::Ares.Player_Android.Resource.String.NoDeviceDriver;
			global::Ares.Players_Android.Resource.String.NoEaxError = global::Ares.Player_Android.Resource.String.NoEaxError;
			global::Ares.Players_Android.Resource.String.NoFxError = global::Ares.Player_Android.Resource.String.NoFxError;
			global::Ares.Players_Android.Resource.String.NoHwError = global::Ares.Player_Android.Resource.String.NoHwError;
			global::Ares.Players_Android.Resource.String.NoPlayError = global::Ares.Player_Android.Resource.String.NoPlayError;
			global::Ares.Players_Android.Resource.String.NotAudioError = global::Ares.Player_Android.Resource.String.NotAudioError;
			global::Ares.Players_Android.Resource.String.NotFileError = global::Ares.Player_Android.Resource.String.NotFileError;
			global::Ares.Players_Android.Resource.String.PingReceived = global::Ares.Player_Android.Resource.String.PingReceived;
			global::Ares.Players_Android.Resource.String.PingTimeout = global::Ares.Player_Android.Resource.String.PingTimeout;
			global::Ares.Players_Android.Resource.String.PlayError = global::Ares.Player_Android.Resource.String.PlayError;
			global::Ares.Players_Android.Resource.String.PlayingError = global::Ares.Player_Android.Resource.String.PlayingError;
			global::Ares.Players_Android.Resource.String.PlaylistNotFound = global::Ares.Player_Android.Resource.String.PlaylistNotFound;
			global::Ares.Players_Android.Resource.String.PositionError = global::Ares.Player_Android.Resource.String.PositionError;
			global::Ares.Players_Android.Resource.String.ReferencedElementNotFound = global::Ares.Player_Android.Resource.String.ReferencedElementNotFound;
			global::Ares.Players_Android.Resource.String.SetEffectError = global::Ares.Player_Android.Resource.String.SetEffectError;
			global::Ares.Players_Android.Resource.String.SetVolumeError = global::Ares.Player_Android.Resource.String.SetVolumeError;
			global::Ares.Players_Android.Resource.String.SpeakerError = global::Ares.Player_Android.Resource.String.SpeakerError;
			global::Ares.Players_Android.Resource.String.SpeakerNotAvailable = global::Ares.Player_Android.Resource.String.SpeakerNotAvailable;
			global::Ares.Players_Android.Resource.String.StartBroadcast = global::Ares.Player_Android.Resource.String.StartBroadcast;
			global::Ares.Players_Android.Resource.String.StartedElementNotFound = global::Ares.Player_Android.Resource.String.StartedElementNotFound;
			global::Ares.Players_Android.Resource.String.StopBroadcast = global::Ares.Player_Android.Resource.String.StopBroadcast;
			global::Ares.Players_Android.Resource.String.StoppedElementNotFound = global::Ares.Player_Android.Resource.String.StoppedElementNotFound;
			global::Ares.Players_Android.Resource.String.StreamingError = global::Ares.Player_Android.Resource.String.StreamingError;
			global::Ares.Players_Android.Resource.String.TagNotFound = global::Ares.Player_Android.Resource.String.TagNotFound;
			global::Ares.Players_Android.Resource.String.TaggedMusic = global::Ares.Player_Android.Resource.String.TaggedMusic;
			global::Ares.Players_Android.Resource.String.TagsDbError = global::Ares.Player_Android.Resource.String.TagsDbError;
			global::Ares.Players_Android.Resource.String.UDPError = global::Ares.Player_Android.Resource.String.UDPError;
			global::Ares.Players_Android.Resource.String.UDPSending = global::Ares.Player_Android.Resource.String.UDPSending;
			global::Ares.Players_Android.Resource.String.UnexpectedError = global::Ares.Player_Android.Resource.String.UnexpectedError;
			global::Ares.Players_Android.Resource.String.VolumeCommandReceived = global::Ares.Player_Android.Resource.String.VolumeCommandReceived;
			global::Ares.Players_Android.Resource.String.VolumeOutOfRange = global::Ares.Player_Android.Resource.String.VolumeOutOfRange;
			global::Ares.Players_Android.Resource.String.WrongClientLength = global::Ares.Player_Android.Resource.String.WrongClientLength;
			global::Ares.Players_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.Playing_Android.Resource.String.Ares = global::Ares.Player_Android.Resource.String.Ares;
			global::Ares.Playing_Android.Resource.String.AwaitedElementNotFound = global::Ares.Player_Android.Resource.String.AwaitedElementNotFound;
			global::Ares.Playing_Android.Resource.String.BassAacLoadFail = global::Ares.Player_Android.Resource.String.BassAacLoadFail;
			global::Ares.Playing_Android.Resource.String.BassDeviceAlready = global::Ares.Player_Android.Resource.String.BassDeviceAlready;
			global::Ares.Playing_Android.Resource.String.BassDeviceDriver = global::Ares.Player_Android.Resource.String.BassDeviceDriver;
			global::Ares.Playing_Android.Resource.String.BassDeviceFormat = global::Ares.Player_Android.Resource.String.BassDeviceFormat;
			global::Ares.Playing_Android.Resource.String.BassDeviceInfo = global::Ares.Player_Android.Resource.String.BassDeviceInfo;
			global::Ares.Playing_Android.Resource.String.BassDeviceInvalid = global::Ares.Player_Android.Resource.String.BassDeviceInvalid;
			global::Ares.Playing_Android.Resource.String.BassFlacLoadFail = global::Ares.Player_Android.Resource.String.BassFlacLoadFail;
			global::Ares.Playing_Android.Resource.String.BassFxLoadFail = global::Ares.Player_Android.Resource.String.BassFxLoadFail;
			global::Ares.Playing_Android.Resource.String.BassInitFail = global::Ares.Player_Android.Resource.String.BassInitFail;
			global::Ares.Playing_Android.Resource.String.BassLoadFail = global::Ares.Player_Android.Resource.String.BassLoadFail;
			global::Ares.Playing_Android.Resource.String.BassNo3D = global::Ares.Player_Android.Resource.String.BassNo3D;
			global::Ares.Playing_Android.Resource.String.BassNoMem = global::Ares.Player_Android.Resource.String.BassNoMem;
			global::Ares.Playing_Android.Resource.String.BassOpusLoadFail = global::Ares.Player_Android.Resource.String.BassOpusLoadFail;
			global::Ares.Playing_Android.Resource.String.BassUnknown = global::Ares.Player_Android.Resource.String.BassUnknown;
			global::Ares.Playing_Android.Resource.String.BufLostError = global::Ares.Player_Android.Resource.String.BufLostError;
			global::Ares.Playing_Android.Resource.String.CannotPlayURLS = global::Ares.Player_Android.Resource.String.CannotPlayURLS;
			global::Ares.Playing_Android.Resource.String.CodecError = global::Ares.Player_Android.Resource.String.CodecError;
			global::Ares.Playing_Android.Resource.String.ConditionElementNotFound = global::Ares.Player_Android.Resource.String.ConditionElementNotFound;
			global::Ares.Playing_Android.Resource.String.CreateError = global::Ares.Player_Android.Resource.String.CreateError;
			global::Ares.Playing_Android.Resource.String.Default = global::Ares.Player_Android.Resource.String.Default;
			global::Ares.Playing_Android.Resource.String.DeviceDisabled = global::Ares.Player_Android.Resource.String.DeviceDisabled;
			global::Ares.Playing_Android.Resource.String.DeviceEnabled = global::Ares.Player_Android.Resource.String.DeviceEnabled;
			global::Ares.Playing_Android.Resource.String.DeviceError = global::Ares.Player_Android.Resource.String.DeviceError;
			global::Ares.Playing_Android.Resource.String.DriverError = global::Ares.Player_Android.Resource.String.DriverError;
			global::Ares.Playing_Android.Resource.String.DxError = global::Ares.Player_Android.Resource.String.DxError;
			global::Ares.Playing_Android.Resource.String.EndedError = global::Ares.Player_Android.Resource.String.EndedError;
			global::Ares.Playing_Android.Resource.String.ErrorReadingPlaylist = global::Ares.Player_Android.Resource.String.ErrorReadingPlaylist;
			global::Ares.Playing_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Playing_Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.Playing_Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.Playing_Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.Playing_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Playing_Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.Playing_Android.Resource.String.FileNotFound = global::Ares.Player_Android.Resource.String.FileNotFound;
			global::Ares.Playing_Android.Resource.String.FileOpenError = global::Ares.Player_Android.Resource.String.FileOpenError;
			global::Ares.Playing_Android.Resource.String.FilePlayingError = global::Ares.Player_Android.Resource.String.FilePlayingError;
			global::Ares.Playing_Android.Resource.String.FileformError = global::Ares.Player_Android.Resource.String.FileformError;
			global::Ares.Playing_Android.Resource.String.FormatError = global::Ares.Player_Android.Resource.String.FormatError;
			global::Ares.Playing_Android.Resource.String.FreqError = global::Ares.Player_Android.Resource.String.FreqError;
			global::Ares.Playing_Android.Resource.String.HandleError = global::Ares.Player_Android.Resource.String.HandleError;
			global::Ares.Playing_Android.Resource.String.IllParamError = global::Ares.Player_Android.Resource.String.IllParamError;
			global::Ares.Playing_Android.Resource.String.IllTypeError = global::Ares.Player_Android.Resource.String.IllTypeError;
			global::Ares.Playing_Android.Resource.String.ImportOverwrite = global::Ares.Player_Android.Resource.String.ImportOverwrite;
			global::Ares.Playing_Android.Resource.String.InvalidImportFile = global::Ares.Player_Android.Resource.String.InvalidImportFile;
			global::Ares.Playing_Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.Playing_Android.Resource.String.MemError = global::Ares.Player_Android.Resource.String.MemError;
			global::Ares.Playing_Android.Resource.String.No3DError = global::Ares.Player_Android.Resource.String.No3DError;
			global::Ares.Playing_Android.Resource.String.NoChanError = global::Ares.Player_Android.Resource.String.NoChanError;
			global::Ares.Playing_Android.Resource.String.NoDevice = global::Ares.Player_Android.Resource.String.NoDevice;
			global::Ares.Playing_Android.Resource.String.NoDeviceDriver = global::Ares.Player_Android.Resource.String.NoDeviceDriver;
			global::Ares.Playing_Android.Resource.String.NoEaxError = global::Ares.Player_Android.Resource.String.NoEaxError;
			global::Ares.Playing_Android.Resource.String.NoFxError = global::Ares.Player_Android.Resource.String.NoFxError;
			global::Ares.Playing_Android.Resource.String.NoHwError = global::Ares.Player_Android.Resource.String.NoHwError;
			global::Ares.Playing_Android.Resource.String.NoPlayError = global::Ares.Player_Android.Resource.String.NoPlayError;
			global::Ares.Playing_Android.Resource.String.NotAudioError = global::Ares.Player_Android.Resource.String.NotAudioError;
			global::Ares.Playing_Android.Resource.String.NotFileError = global::Ares.Player_Android.Resource.String.NotFileError;
			global::Ares.Playing_Android.Resource.String.PlayingError = global::Ares.Player_Android.Resource.String.PlayingError;
			global::Ares.Playing_Android.Resource.String.PlaylistNotFound = global::Ares.Player_Android.Resource.String.PlaylistNotFound;
			global::Ares.Playing_Android.Resource.String.PositionError = global::Ares.Player_Android.Resource.String.PositionError;
			global::Ares.Playing_Android.Resource.String.ReferencedElementNotFound = global::Ares.Player_Android.Resource.String.ReferencedElementNotFound;
			global::Ares.Playing_Android.Resource.String.SetEffectError = global::Ares.Player_Android.Resource.String.SetEffectError;
			global::Ares.Playing_Android.Resource.String.SetVolumeError = global::Ares.Player_Android.Resource.String.SetVolumeError;
			global::Ares.Playing_Android.Resource.String.SpeakerError = global::Ares.Player_Android.Resource.String.SpeakerError;
			global::Ares.Playing_Android.Resource.String.SpeakerNotAvailable = global::Ares.Player_Android.Resource.String.SpeakerNotAvailable;
			global::Ares.Playing_Android.Resource.String.StartedElementNotFound = global::Ares.Player_Android.Resource.String.StartedElementNotFound;
			global::Ares.Playing_Android.Resource.String.StoppedElementNotFound = global::Ares.Player_Android.Resource.String.StoppedElementNotFound;
			global::Ares.Playing_Android.Resource.String.StreamingError = global::Ares.Player_Android.Resource.String.StreamingError;
			global::Ares.Playing_Android.Resource.String.TagNotFound = global::Ares.Player_Android.Resource.String.TagNotFound;
			global::Ares.Playing_Android.Resource.String.TaggedMusic = global::Ares.Player_Android.Resource.String.TaggedMusic;
			global::Ares.Playing_Android.Resource.String.TagsDbError = global::Ares.Player_Android.Resource.String.TagsDbError;
			global::Ares.Playing_Android.Resource.String.UnexpectedError = global::Ares.Player_Android.Resource.String.UnexpectedError;
			global::Ares.Playing_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.Settings_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Settings_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Settings_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int filterChoices = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ares = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int eventlogError = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int clearButton = 2131230726;
			
			// aapt resource value: 0x7f080011
			public const int controllerButton = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int controllerVIew = 2131230735;
			
			// aapt resource value: 0x7f080005
			public const int filterSpinner = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout2 = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int messageIcon = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int messageLine = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int messagesButton = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int messagesList = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int messages_fragment = 2131230721;
			
			// aapt resource value: 0x7f080013
			public const int projectView = 2131230739;
			
			// aapt resource value: 0x7f08000c
			public const int serviceButton = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int serviceView = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int service_fragment = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int space1 = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int space2 = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int textView1 = 2131230724;
			
			// aapt resource value: 0x7f08000e
			public const int textView3 = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int textView5 = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Messages = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MessagesFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MessagesListEntry = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ServiceFragment = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05004d
			public const int Ares = 2131034189;
			
			// aapt resource value: 0x7f050055
			public const int AwaitedElementNotFound = 2131034197;
			
			// aapt resource value: 0x7f050025
			public const int BassAacLoadFail = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int BassDeviceAlready = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int BassDeviceDriver = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int BassDeviceFormat = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int BassDeviceInfo = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int BassDeviceInvalid = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int BassFlacLoadFail = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int BassFxLoadFail = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int BassInitFail = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int BassLoadFail = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int BassNo3D = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int BassNoMem = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int BassOpusLoadFail = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int BassUnknown = 2131034162;
			
			// aapt resource value: 0x7f050003
			public const int BufLostError = 2131034115;
			
			// aapt resource value: 0x7f050051
			public const int CannotPlayURLS = 2131034193;
			
			// aapt resource value: 0x7f050038
			public const int ClientConnected = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int ClientDisconnected = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int ClientLengthReceived = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int ClientListenError = 2131034171;
			
			// aapt resource value: 0x7f050004
			public const int CodecError = 2131034116;
			
			// aapt resource value: 0x7f05003c
			public const int CommandReceived = 2131034172;
			
			// aapt resource value: 0x7f050054
			public const int ConditionElementNotFound = 2131034196;
			
			// aapt resource value: 0x7f050005
			public const int CreateError = 2131034117;
			
			// aapt resource value: 0x7f050066
			public const int Debug = 2131034214;
			
			// aapt resource value: 0x7f050037
			public const int Default = 2131034167;
			
			// aapt resource value: 0x7f050033
			public const int DeviceDisabled = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int DeviceEnabled = 2131034164;
			
			// aapt resource value: 0x7f050006
			public const int DeviceError = 2131034118;
			
			// aapt resource value: 0x7f05003d
			public const int DisconnectingClient = 2131034173;
			
			// aapt resource value: 0x7f050007
			public const int DriverError = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int DxError = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int EndedError = 2131034121;
			
			// aapt resource value: 0x7f050069
			public const int Error = 2131034217;
			
			// aapt resource value: 0x7f050052
			public const int ErrorReadingPlaylist = 2131034194;
			
			// aapt resource value: 0x7f050001
			public const int ExpectedAttribute = 2131034113;
			
			// aapt resource value: 0x7f05005a
			public const int ExpectedContent = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int ExpectedDouble = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int ExpectedElement = 2131034204;
			
			// aapt resource value: 0x7f050002
			public const int ExpectedInteger = 2131034114;
			
			// aapt resource value: 0x7f05005d
			public const int FileNameMustBeSet = 2131034205;
			
			// aapt resource value: 0x7f05004e
			public const int FileNotFound = 2131034190;
			
			// aapt resource value: 0x7f05000b
			public const int FileOpenError = 2131034123;
			
			// aapt resource value: 0x7f05001e
			public const int FilePlayingError = 2131034142;
			
			// aapt resource value: 0x7f05000a
			public const int FileformError = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int FormatError = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int FreqError = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int HandleError = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int IllParamError = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int IllTypeError = 2131034128;
			
			// aapt resource value: 0x7f05004f
			public const int ImportOverwrite = 2131034191;
			
			// aapt resource value: 0x7f050067
			public const int Info = 2131034215;
			
			// aapt resource value: 0x7f050050
			public const int InvalidImportFile = 2131034192;
			
			// aapt resource value: 0x7f05003e
			public const int InvalidKeyCode = 2131034174;
			
			// aapt resource value: 0x7f05005e
			public const int InvalidVolume = 2131034206;
			
			// aapt resource value: 0x7f05003f
			public const int KeyListenError = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int KeyReceived = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int LengthTooHigh = 2131034177;
			
			// aapt resource value: 0x7f050011
			public const int MemError = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int No3DError = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int NoChanError = 2131034131;
			
			// aapt resource value: 0x7f050042
			public const int NoClientID = 2131034178;
			
			// aapt resource value: 0x7f050035
			public const int NoDevice = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int NoDeviceDriver = 2131034166;
			
			// aapt resource value: 0x7f050014
			public const int NoEaxError = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int NoFxError = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int NoHwError = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int NoPlayError = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int NotAudioError = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int NotFileError = 2131034137;
			
			// aapt resource value: 0x7f050043
			public const int PingReceived = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int PingTimeout = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int PlayError = 2131034181;
			
			// aapt resource value: 0x7f05001a
			public const int PlayingError = 2131034138;
			
			// aapt resource value: 0x7f050053
			public const int PlaylistNotFound = 2131034195;
			
			// aapt resource value: 0x7f05001b
			public const int PositionError = 2131034139;
			
			// aapt resource value: 0x7f050058
			public const int ReferencedElementNotFound = 2131034200;
			
			// aapt resource value: 0x7f050020
			public const int SetEffectError = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int SetVolumeError = 2131034143;
			
			// aapt resource value: 0x7f05001c
			public const int SpeakerError = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int SpeakerNotAvailable = 2131034145;
			
			// aapt resource value: 0x7f050046
			public const int StartBroadcast = 2131034182;
			
			// aapt resource value: 0x7f050056
			public const int StartedElementNotFound = 2131034198;
			
			// aapt resource value: 0x7f050047
			public const int StopBroadcast = 2131034183;
			
			// aapt resource value: 0x7f050057
			public const int StoppedElementNotFound = 2131034199;
			
			// aapt resource value: 0x7f050022
			public const int StreamingError = 2131034146;
			
			// aapt resource value: 0x7f050059
			public const int TagNotFound = 2131034201;
			
			// aapt resource value: 0x7f050024
			public const int TaggedMusic = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int TagsDbError = 2131034147;
			
			// aapt resource value: 0x7f050048
			public const int UDPError = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int UDPSending = 2131034185;
			
			// aapt resource value: 0x7f05001d
			public const int UnexpectedError = 2131034141;
			
			// aapt resource value: 0x7f05004a
			public const int VolumeCommandReceived = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int VolumeOutOfRange = 2131034187;
			
			// aapt resource value: 0x7f050068
			public const int Warning = 2131034216;
			
			// aapt resource value: 0x7f05004c
			public const int WrongClientLength = 2131034188;
			
			// aapt resource value: 0x7f05005f
			public const int app_name = 2131034207;
			
			// aapt resource value: 0x7f05007d
			public const int clear = 2131034237;
			
			// aapt resource value: 0x7f05006b
			public const int connected_with = 2131034219;
			
			// aapt resource value: 0x7f050074
			public const int controller = 2131034228;
			
			// aapt resource value: 0x7f050075
			public const int controller_status = 2131034229;
			
			// aapt resource value: 0x7f05006d
			public const int directory_error = 2131034221;
			
			// aapt resource value: 0x7f05007c
			public const int filter = 2131034236;
			
			// aapt resource value: 0x7f050065
			public const int import_error = 2131034213;
			
			// aapt resource value: 0x7f050071
			public const int importing_project = 2131034225;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050064
			public const int load_error = 2131034212;
			
			// aapt resource value: 0x7f05006f
			public const int loaded_project = 2131034223;
			
			// aapt resource value: 0x7f05007e
			public const int messages = 2131034238;
			
			// aapt resource value: 0x7f050060
			public const int no_ip_address = 2131034208;
			
			// aapt resource value: 0x7f050070
			public const int no_project = 2131034224;
			
			// aapt resource value: 0x7f050063
			public const int no_settings = 2131034211;
			
			// aapt resource value: 0x7f050061
			public const int no_status_info_error = 2131034209;
			
			// aapt resource value: 0x7f05006c
			public const int not_connected = 2131034220;
			
			// aapt resource value: 0x7f050072
			public const int player_service = 2131034226;
			
			// aapt resource value: 0x7f050077
			public const int project = 2131034231;
			
			// aapt resource value: 0x7f05007a
			public const int running = 2131034234;
			
			// aapt resource value: 0x7f05006a
			public const int service_error = 2131034218;
			
			// aapt resource value: 0x7f05006e
			public const int service_running = 2131034222;
			
			// aapt resource value: 0x7f050073
			public const int service_status = 2131034227;
			
			// aapt resource value: 0x7f050078
			public const int start = 2131034232;
			
			// aapt resource value: 0x7f050076
			public const int start_controller = 2131034230;
			
			// aapt resource value: 0x7f050079
			public const int stop = 2131034233;
			
			// aapt resource value: 0x7f05007b
			public const int stopped = 2131034235;
			
			// aapt resource value: 0x7f050062
			public const int tags_db_error = 2131034210;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
