#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ares.Player_Android.Resource", IsApplication=true)]

namespace Ares.Player_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Ares.Data.Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Data.Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.Data.Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.Data.Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.Data.Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Data.Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.Data.Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.Data.Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.ModelInfo_Android.Resource.String.Ares = global::Ares.Player_Android.Resource.String.Ares;
			global::Ares.ModelInfo_Android.Resource.String.AwaitedElementNotFound = global::Ares.Player_Android.Resource.String.AwaitedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.CannotPlayURLS = global::Ares.Player_Android.Resource.String.CannotPlayURLS;
			global::Ares.ModelInfo_Android.Resource.String.ConditionElementNotFound = global::Ares.Player_Android.Resource.String.ConditionElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.ErrorReadingPlaylist = global::Ares.Player_Android.Resource.String.ErrorReadingPlaylist;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.ModelInfo_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.ModelInfo_Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.ModelInfo_Android.Resource.String.FileNotFound = global::Ares.Player_Android.Resource.String.FileNotFound;
			global::Ares.ModelInfo_Android.Resource.String.ImportOverwrite = global::Ares.Player_Android.Resource.String.ImportOverwrite;
			global::Ares.ModelInfo_Android.Resource.String.InvalidImportFile = global::Ares.Player_Android.Resource.String.InvalidImportFile;
			global::Ares.ModelInfo_Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.ModelInfo_Android.Resource.String.PlaylistNotFound = global::Ares.Player_Android.Resource.String.PlaylistNotFound;
			global::Ares.ModelInfo_Android.Resource.String.ReferencedElementNotFound = global::Ares.Player_Android.Resource.String.ReferencedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.StartedElementNotFound = global::Ares.Player_Android.Resource.String.StartedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.StoppedElementNotFound = global::Ares.Player_Android.Resource.String.StoppedElementNotFound;
			global::Ares.ModelInfo_Android.Resource.String.TagNotFound = global::Ares.Player_Android.Resource.String.TagNotFound;
			global::Ares.ModelInfo_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.Players_Android.Resource.String.BassAacLoadFail = global::Ares.Player_Android.Resource.String.BassAacLoadFail;
			global::Ares.Players_Android.Resource.String.BassDeviceAlready = global::Ares.Player_Android.Resource.String.BassDeviceAlready;
			global::Ares.Players_Android.Resource.String.BassDeviceDriver = global::Ares.Player_Android.Resource.String.BassDeviceDriver;
			global::Ares.Players_Android.Resource.String.BassDeviceFormat = global::Ares.Player_Android.Resource.String.BassDeviceFormat;
			global::Ares.Players_Android.Resource.String.BassDeviceInfo = global::Ares.Player_Android.Resource.String.BassDeviceInfo;
			global::Ares.Players_Android.Resource.String.BassDeviceInvalid = global::Ares.Player_Android.Resource.String.BassDeviceInvalid;
			global::Ares.Players_Android.Resource.String.BassFlacLoadFail = global::Ares.Player_Android.Resource.String.BassFlacLoadFail;
			global::Ares.Players_Android.Resource.String.BassFxLoadFail = global::Ares.Player_Android.Resource.String.BassFxLoadFail;
			global::Ares.Players_Android.Resource.String.BassInitFail = global::Ares.Player_Android.Resource.String.BassInitFail;
			global::Ares.Players_Android.Resource.String.BassLoadFail = global::Ares.Player_Android.Resource.String.BassLoadFail;
			global::Ares.Players_Android.Resource.String.BassNo3D = global::Ares.Player_Android.Resource.String.BassNo3D;
			global::Ares.Players_Android.Resource.String.BassNoMem = global::Ares.Player_Android.Resource.String.BassNoMem;
			global::Ares.Players_Android.Resource.String.BassOpusLoadFail = global::Ares.Player_Android.Resource.String.BassOpusLoadFail;
			global::Ares.Players_Android.Resource.String.BassUnknown = global::Ares.Player_Android.Resource.String.BassUnknown;
			global::Ares.Players_Android.Resource.String.BufLostError = global::Ares.Player_Android.Resource.String.BufLostError;
			global::Ares.Players_Android.Resource.String.ClientConnected = global::Ares.Player_Android.Resource.String.ClientConnected;
			global::Ares.Players_Android.Resource.String.ClientDisconnected = global::Ares.Player_Android.Resource.String.ClientDisconnected;
			global::Ares.Players_Android.Resource.String.ClientLengthReceived = global::Ares.Player_Android.Resource.String.ClientLengthReceived;
			global::Ares.Players_Android.Resource.String.ClientListenError = global::Ares.Player_Android.Resource.String.ClientListenError;
			global::Ares.Players_Android.Resource.String.ClientSendError = global::Ares.Player_Android.Resource.String.ClientSendError;
			global::Ares.Players_Android.Resource.String.CodecError = global::Ares.Player_Android.Resource.String.CodecError;
			global::Ares.Players_Android.Resource.String.CommandReceived = global::Ares.Player_Android.Resource.String.CommandReceived;
			global::Ares.Players_Android.Resource.String.CreateError = global::Ares.Player_Android.Resource.String.CreateError;
			global::Ares.Players_Android.Resource.String.Default = global::Ares.Player_Android.Resource.String.Default;
			global::Ares.Players_Android.Resource.String.DeviceDisabled = global::Ares.Player_Android.Resource.String.DeviceDisabled;
			global::Ares.Players_Android.Resource.String.DeviceEnabled = global::Ares.Player_Android.Resource.String.DeviceEnabled;
			global::Ares.Players_Android.Resource.String.DeviceError = global::Ares.Player_Android.Resource.String.DeviceError;
			global::Ares.Players_Android.Resource.String.DisconnectingClient = global::Ares.Player_Android.Resource.String.DisconnectingClient;
			global::Ares.Players_Android.Resource.String.DriverError = global::Ares.Player_Android.Resource.String.DriverError;
			global::Ares.Players_Android.Resource.String.DxError = global::Ares.Player_Android.Resource.String.DxError;
			global::Ares.Players_Android.Resource.String.EndedError = global::Ares.Player_Android.Resource.String.EndedError;
			global::Ares.Players_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Players_Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.Players_Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.Players_Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.Players_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Players_Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.Players_Android.Resource.String.FileOpenError = global::Ares.Player_Android.Resource.String.FileOpenError;
			global::Ares.Players_Android.Resource.String.FilePlayingError = global::Ares.Player_Android.Resource.String.FilePlayingError;
			global::Ares.Players_Android.Resource.String.FileformError = global::Ares.Player_Android.Resource.String.FileformError;
			global::Ares.Players_Android.Resource.String.FormatError = global::Ares.Player_Android.Resource.String.FormatError;
			global::Ares.Players_Android.Resource.String.FreqError = global::Ares.Player_Android.Resource.String.FreqError;
			global::Ares.Players_Android.Resource.String.HandleError = global::Ares.Player_Android.Resource.String.HandleError;
			global::Ares.Players_Android.Resource.String.IllParamError = global::Ares.Player_Android.Resource.String.IllParamError;
			global::Ares.Players_Android.Resource.String.IllTypeError = global::Ares.Player_Android.Resource.String.IllTypeError;
			global::Ares.Players_Android.Resource.String.InvalidKeyCode = global::Ares.Player_Android.Resource.String.InvalidKeyCode;
			global::Ares.Players_Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.Players_Android.Resource.String.KeyListenError = global::Ares.Player_Android.Resource.String.KeyListenError;
			global::Ares.Players_Android.Resource.String.KeyReceived = global::Ares.Player_Android.Resource.String.KeyReceived;
			global::Ares.Players_Android.Resource.String.LengthTooHigh = global::Ares.Player_Android.Resource.String.LengthTooHigh;
			global::Ares.Players_Android.Resource.String.MemError = global::Ares.Player_Android.Resource.String.MemError;
			global::Ares.Players_Android.Resource.String.No3DError = global::Ares.Player_Android.Resource.String.No3DError;
			global::Ares.Players_Android.Resource.String.NoChanError = global::Ares.Player_Android.Resource.String.NoChanError;
			global::Ares.Players_Android.Resource.String.NoClientID = global::Ares.Player_Android.Resource.String.NoClientID;
			global::Ares.Players_Android.Resource.String.NoDevice = global::Ares.Player_Android.Resource.String.NoDevice;
			global::Ares.Players_Android.Resource.String.NoDeviceDriver = global::Ares.Player_Android.Resource.String.NoDeviceDriver;
			global::Ares.Players_Android.Resource.String.NoEaxError = global::Ares.Player_Android.Resource.String.NoEaxError;
			global::Ares.Players_Android.Resource.String.NoFxError = global::Ares.Player_Android.Resource.String.NoFxError;
			global::Ares.Players_Android.Resource.String.NoHwError = global::Ares.Player_Android.Resource.String.NoHwError;
			global::Ares.Players_Android.Resource.String.NoPlayError = global::Ares.Player_Android.Resource.String.NoPlayError;
			global::Ares.Players_Android.Resource.String.NotAudioError = global::Ares.Player_Android.Resource.String.NotAudioError;
			global::Ares.Players_Android.Resource.String.NotFileError = global::Ares.Player_Android.Resource.String.NotFileError;
			global::Ares.Players_Android.Resource.String.PingReceived = global::Ares.Player_Android.Resource.String.PingReceived;
			global::Ares.Players_Android.Resource.String.PingTimeout = global::Ares.Player_Android.Resource.String.PingTimeout;
			global::Ares.Players_Android.Resource.String.PlayError = global::Ares.Player_Android.Resource.String.PlayError;
			global::Ares.Players_Android.Resource.String.PlayingError = global::Ares.Player_Android.Resource.String.PlayingError;
			global::Ares.Players_Android.Resource.String.PositionError = global::Ares.Player_Android.Resource.String.PositionError;
			global::Ares.Players_Android.Resource.String.SetEffectError = global::Ares.Player_Android.Resource.String.SetEffectError;
			global::Ares.Players_Android.Resource.String.SetVolumeError = global::Ares.Player_Android.Resource.String.SetVolumeError;
			global::Ares.Players_Android.Resource.String.SpeakerError = global::Ares.Player_Android.Resource.String.SpeakerError;
			global::Ares.Players_Android.Resource.String.SpeakerNotAvailable = global::Ares.Player_Android.Resource.String.SpeakerNotAvailable;
			global::Ares.Players_Android.Resource.String.StartBroadcast = global::Ares.Player_Android.Resource.String.StartBroadcast;
			global::Ares.Players_Android.Resource.String.StopBroadcast = global::Ares.Player_Android.Resource.String.StopBroadcast;
			global::Ares.Players_Android.Resource.String.StreamingError = global::Ares.Player_Android.Resource.String.StreamingError;
			global::Ares.Players_Android.Resource.String.TaggedMusic = global::Ares.Player_Android.Resource.String.TaggedMusic;
			global::Ares.Players_Android.Resource.String.TagsDbError = global::Ares.Player_Android.Resource.String.TagsDbError;
			global::Ares.Players_Android.Resource.String.UDPError = global::Ares.Player_Android.Resource.String.UDPError;
			global::Ares.Players_Android.Resource.String.UDPSending = global::Ares.Player_Android.Resource.String.UDPSending;
			global::Ares.Players_Android.Resource.String.UnexpectedError = global::Ares.Player_Android.Resource.String.UnexpectedError;
			global::Ares.Players_Android.Resource.String.VolumeCommandReceived = global::Ares.Player_Android.Resource.String.VolumeCommandReceived;
			global::Ares.Players_Android.Resource.String.VolumeOutOfRange = global::Ares.Player_Android.Resource.String.VolumeOutOfRange;
			global::Ares.Players_Android.Resource.String.WrongClientLength = global::Ares.Player_Android.Resource.String.WrongClientLength;
			global::Ares.Players_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.Playing_Android.Resource.String.Ares = global::Ares.Player_Android.Resource.String.Ares;
			global::Ares.Playing_Android.Resource.String.AwaitedElementNotFound = global::Ares.Player_Android.Resource.String.AwaitedElementNotFound;
			global::Ares.Playing_Android.Resource.String.BassAacLoadFail = global::Ares.Player_Android.Resource.String.BassAacLoadFail;
			global::Ares.Playing_Android.Resource.String.BassDeviceAlready = global::Ares.Player_Android.Resource.String.BassDeviceAlready;
			global::Ares.Playing_Android.Resource.String.BassDeviceDriver = global::Ares.Player_Android.Resource.String.BassDeviceDriver;
			global::Ares.Playing_Android.Resource.String.BassDeviceFormat = global::Ares.Player_Android.Resource.String.BassDeviceFormat;
			global::Ares.Playing_Android.Resource.String.BassDeviceInfo = global::Ares.Player_Android.Resource.String.BassDeviceInfo;
			global::Ares.Playing_Android.Resource.String.BassDeviceInvalid = global::Ares.Player_Android.Resource.String.BassDeviceInvalid;
			global::Ares.Playing_Android.Resource.String.BassFlacLoadFail = global::Ares.Player_Android.Resource.String.BassFlacLoadFail;
			global::Ares.Playing_Android.Resource.String.BassFxLoadFail = global::Ares.Player_Android.Resource.String.BassFxLoadFail;
			global::Ares.Playing_Android.Resource.String.BassInitFail = global::Ares.Player_Android.Resource.String.BassInitFail;
			global::Ares.Playing_Android.Resource.String.BassLoadFail = global::Ares.Player_Android.Resource.String.BassLoadFail;
			global::Ares.Playing_Android.Resource.String.BassNo3D = global::Ares.Player_Android.Resource.String.BassNo3D;
			global::Ares.Playing_Android.Resource.String.BassNoMem = global::Ares.Player_Android.Resource.String.BassNoMem;
			global::Ares.Playing_Android.Resource.String.BassOpusLoadFail = global::Ares.Player_Android.Resource.String.BassOpusLoadFail;
			global::Ares.Playing_Android.Resource.String.BassUnknown = global::Ares.Player_Android.Resource.String.BassUnknown;
			global::Ares.Playing_Android.Resource.String.BufLostError = global::Ares.Player_Android.Resource.String.BufLostError;
			global::Ares.Playing_Android.Resource.String.CannotPlayURLS = global::Ares.Player_Android.Resource.String.CannotPlayURLS;
			global::Ares.Playing_Android.Resource.String.CodecError = global::Ares.Player_Android.Resource.String.CodecError;
			global::Ares.Playing_Android.Resource.String.ConditionElementNotFound = global::Ares.Player_Android.Resource.String.ConditionElementNotFound;
			global::Ares.Playing_Android.Resource.String.CreateError = global::Ares.Player_Android.Resource.String.CreateError;
			global::Ares.Playing_Android.Resource.String.Default = global::Ares.Player_Android.Resource.String.Default;
			global::Ares.Playing_Android.Resource.String.DeviceDisabled = global::Ares.Player_Android.Resource.String.DeviceDisabled;
			global::Ares.Playing_Android.Resource.String.DeviceEnabled = global::Ares.Player_Android.Resource.String.DeviceEnabled;
			global::Ares.Playing_Android.Resource.String.DeviceError = global::Ares.Player_Android.Resource.String.DeviceError;
			global::Ares.Playing_Android.Resource.String.DriverError = global::Ares.Player_Android.Resource.String.DriverError;
			global::Ares.Playing_Android.Resource.String.DxError = global::Ares.Player_Android.Resource.String.DxError;
			global::Ares.Playing_Android.Resource.String.EndedError = global::Ares.Player_Android.Resource.String.EndedError;
			global::Ares.Playing_Android.Resource.String.ErrorReadingPlaylist = global::Ares.Player_Android.Resource.String.ErrorReadingPlaylist;
			global::Ares.Playing_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Playing_Android.Resource.String.ExpectedContent = global::Ares.Player_Android.Resource.String.ExpectedContent;
			global::Ares.Playing_Android.Resource.String.ExpectedDouble = global::Ares.Player_Android.Resource.String.ExpectedDouble;
			global::Ares.Playing_Android.Resource.String.ExpectedElement = global::Ares.Player_Android.Resource.String.ExpectedElement;
			global::Ares.Playing_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Playing_Android.Resource.String.FileNameMustBeSet = global::Ares.Player_Android.Resource.String.FileNameMustBeSet;
			global::Ares.Playing_Android.Resource.String.FileNotFound = global::Ares.Player_Android.Resource.String.FileNotFound;
			global::Ares.Playing_Android.Resource.String.FileOpenError = global::Ares.Player_Android.Resource.String.FileOpenError;
			global::Ares.Playing_Android.Resource.String.FilePlayingError = global::Ares.Player_Android.Resource.String.FilePlayingError;
			global::Ares.Playing_Android.Resource.String.FileformError = global::Ares.Player_Android.Resource.String.FileformError;
			global::Ares.Playing_Android.Resource.String.FormatError = global::Ares.Player_Android.Resource.String.FormatError;
			global::Ares.Playing_Android.Resource.String.FreqError = global::Ares.Player_Android.Resource.String.FreqError;
			global::Ares.Playing_Android.Resource.String.HandleError = global::Ares.Player_Android.Resource.String.HandleError;
			global::Ares.Playing_Android.Resource.String.IllParamError = global::Ares.Player_Android.Resource.String.IllParamError;
			global::Ares.Playing_Android.Resource.String.IllTypeError = global::Ares.Player_Android.Resource.String.IllTypeError;
			global::Ares.Playing_Android.Resource.String.ImportOverwrite = global::Ares.Player_Android.Resource.String.ImportOverwrite;
			global::Ares.Playing_Android.Resource.String.InvalidImportFile = global::Ares.Player_Android.Resource.String.InvalidImportFile;
			global::Ares.Playing_Android.Resource.String.InvalidVolume = global::Ares.Player_Android.Resource.String.InvalidVolume;
			global::Ares.Playing_Android.Resource.String.MemError = global::Ares.Player_Android.Resource.String.MemError;
			global::Ares.Playing_Android.Resource.String.No3DError = global::Ares.Player_Android.Resource.String.No3DError;
			global::Ares.Playing_Android.Resource.String.NoChanError = global::Ares.Player_Android.Resource.String.NoChanError;
			global::Ares.Playing_Android.Resource.String.NoDevice = global::Ares.Player_Android.Resource.String.NoDevice;
			global::Ares.Playing_Android.Resource.String.NoDeviceDriver = global::Ares.Player_Android.Resource.String.NoDeviceDriver;
			global::Ares.Playing_Android.Resource.String.NoEaxError = global::Ares.Player_Android.Resource.String.NoEaxError;
			global::Ares.Playing_Android.Resource.String.NoFxError = global::Ares.Player_Android.Resource.String.NoFxError;
			global::Ares.Playing_Android.Resource.String.NoHwError = global::Ares.Player_Android.Resource.String.NoHwError;
			global::Ares.Playing_Android.Resource.String.NoPlayError = global::Ares.Player_Android.Resource.String.NoPlayError;
			global::Ares.Playing_Android.Resource.String.NotAudioError = global::Ares.Player_Android.Resource.String.NotAudioError;
			global::Ares.Playing_Android.Resource.String.NotFileError = global::Ares.Player_Android.Resource.String.NotFileError;
			global::Ares.Playing_Android.Resource.String.PlayingError = global::Ares.Player_Android.Resource.String.PlayingError;
			global::Ares.Playing_Android.Resource.String.PlaylistNotFound = global::Ares.Player_Android.Resource.String.PlaylistNotFound;
			global::Ares.Playing_Android.Resource.String.PositionError = global::Ares.Player_Android.Resource.String.PositionError;
			global::Ares.Playing_Android.Resource.String.ReferencedElementNotFound = global::Ares.Player_Android.Resource.String.ReferencedElementNotFound;
			global::Ares.Playing_Android.Resource.String.SetEffectError = global::Ares.Player_Android.Resource.String.SetEffectError;
			global::Ares.Playing_Android.Resource.String.SetVolumeError = global::Ares.Player_Android.Resource.String.SetVolumeError;
			global::Ares.Playing_Android.Resource.String.SpeakerError = global::Ares.Player_Android.Resource.String.SpeakerError;
			global::Ares.Playing_Android.Resource.String.SpeakerNotAvailable = global::Ares.Player_Android.Resource.String.SpeakerNotAvailable;
			global::Ares.Playing_Android.Resource.String.StartedElementNotFound = global::Ares.Player_Android.Resource.String.StartedElementNotFound;
			global::Ares.Playing_Android.Resource.String.StoppedElementNotFound = global::Ares.Player_Android.Resource.String.StoppedElementNotFound;
			global::Ares.Playing_Android.Resource.String.StreamingError = global::Ares.Player_Android.Resource.String.StreamingError;
			global::Ares.Playing_Android.Resource.String.TagNotFound = global::Ares.Player_Android.Resource.String.TagNotFound;
			global::Ares.Playing_Android.Resource.String.TaggedMusic = global::Ares.Player_Android.Resource.String.TaggedMusic;
			global::Ares.Playing_Android.Resource.String.TagsDbError = global::Ares.Player_Android.Resource.String.TagsDbError;
			global::Ares.Playing_Android.Resource.String.UnexpectedError = global::Ares.Player_Android.Resource.String.UnexpectedError;
			global::Ares.Playing_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
			global::Ares.Settings_Android.Resource.String.ExpectedAttribute = global::Ares.Player_Android.Resource.String.ExpectedAttribute;
			global::Ares.Settings_Android.Resource.String.ExpectedInteger = global::Ares.Player_Android.Resource.String.ExpectedInteger;
			global::Ares.Settings_Android.Resource.String.library_name = global::Ares.Player_Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int filterChoices = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int folderType = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int portType = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ares = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int eventlogError = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int clearButton = 2131296271;
			
			// aapt resource value: 0x7f09001a
			public const int controllerButton = 2131296282;
			
			// aapt resource value: 0x7f090018
			public const int controllerVIew = 2131296280;
			
			// aapt resource value: 0x7f090008
			public const int createButton = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int currentFolderView = 2131296258;
			
			// aapt resource value: 0x7f09000e
			public const int filterSpinner = 2131296270;
			
			// aapt resource value: 0x7f090005
			public const int folderList = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int gridLayout1 = 2131296268;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int linearLayout2 = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout3 = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout5 = 2131296257;
			
			// aapt resource value: 0x7f090020
			public const int menu_about = 2131296288;
			
			// aapt resource value: 0x7f09001e
			public const int menu_settings = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int menu_usage = 2131296287;
			
			// aapt resource value: 0x7f090011
			public const int messageIcon = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int messageLine = 2131296274;
			
			// aapt resource value: 0x7f09000a
			public const int messageTitleView = 2131296266;
			
			// aapt resource value: 0x7f090016
			public const int messagesButton = 2131296278;
			
			// aapt resource value: 0x7f090010
			public const int messagesList = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int messages_fragment = 2131296267;
			
			// aapt resource value: 0x7f09001c
			public const int projectView = 2131296284;
			
			// aapt resource value: 0x7f090003
			public const int selectButton = 2131296259;
			
			// aapt resource value: 0x7f090015
			public const int serviceButton = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int serviceView = 2131296275;
			
			// aapt resource value: 0x7f090009
			public const int service_fragment = 2131296265;
			
			// aapt resource value: 0x7f090014
			public const int space1 = 2131296276;
			
			// aapt resource value: 0x7f090019
			public const int space2 = 2131296281;
			
			// aapt resource value: 0x7f09000d
			public const int textView1 = 2131296269;
			
			// aapt resource value: 0x7f090017
			public const int textView3 = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int textView5 = 2131296283;
			
			// aapt resource value: 0x7f090007
			public const int upButton = 2131296263;
			
			// aapt resource value: 0x7f09001d
			public const int usageText = 2131296285;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FolderBrowser = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FolderListItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Messages = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MessagesFragment = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int MessagesListEntry = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ServiceFragment = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Usage = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int OptionsMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06004e
			public const int Ares = 2131099726;
			
			// aapt resource value: 0x7f060056
			public const int AwaitedElementNotFound = 2131099734;
			
			// aapt resource value: 0x7f060025
			public const int BassAacLoadFail = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int BassDeviceAlready = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int BassDeviceDriver = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int BassDeviceFormat = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int BassDeviceInfo = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int BassDeviceInvalid = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int BassFlacLoadFail = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int BassFxLoadFail = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int BassInitFail = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int BassLoadFail = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int BassNo3D = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int BassNoMem = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int BassOpusLoadFail = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int BassUnknown = 2131099698;
			
			// aapt resource value: 0x7f060003
			public const int BufLostError = 2131099651;
			
			// aapt resource value: 0x7f060052
			public const int CannotPlayURLS = 2131099730;
			
			// aapt resource value: 0x7f060038
			public const int ClientConnected = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int ClientDisconnected = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int ClientLengthReceived = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int ClientListenError = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int ClientSendError = 2131099708;
			
			// aapt resource value: 0x7f060004
			public const int CodecError = 2131099652;
			
			// aapt resource value: 0x7f06003d
			public const int CommandReceived = 2131099709;
			
			// aapt resource value: 0x7f060055
			public const int ConditionElementNotFound = 2131099733;
			
			// aapt resource value: 0x7f060005
			public const int CreateError = 2131099653;
			
			// aapt resource value: 0x7f060067
			public const int Debug = 2131099751;
			
			// aapt resource value: 0x7f060037
			public const int Default = 2131099703;
			
			// aapt resource value: 0x7f060033
			public const int DeviceDisabled = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int DeviceEnabled = 2131099700;
			
			// aapt resource value: 0x7f060006
			public const int DeviceError = 2131099654;
			
			// aapt resource value: 0x7f06003e
			public const int DisconnectingClient = 2131099710;
			
			// aapt resource value: 0x7f060007
			public const int DriverError = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int DxError = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int EndedError = 2131099657;
			
			// aapt resource value: 0x7f06006a
			public const int Error = 2131099754;
			
			// aapt resource value: 0x7f060053
			public const int ErrorReadingPlaylist = 2131099731;
			
			// aapt resource value: 0x7f060001
			public const int ExpectedAttribute = 2131099649;
			
			// aapt resource value: 0x7f06005b
			public const int ExpectedContent = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int ExpectedDouble = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int ExpectedElement = 2131099741;
			
			// aapt resource value: 0x7f060002
			public const int ExpectedInteger = 2131099650;
			
			// aapt resource value: 0x7f06005e
			public const int FileNameMustBeSet = 2131099742;
			
			// aapt resource value: 0x7f06004f
			public const int FileNotFound = 2131099727;
			
			// aapt resource value: 0x7f06000b
			public const int FileOpenError = 2131099659;
			
			// aapt resource value: 0x7f06001e
			public const int FilePlayingError = 2131099678;
			
			// aapt resource value: 0x7f06000a
			public const int FileformError = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int FormatError = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int FreqError = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int HandleError = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int IllParamError = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int IllTypeError = 2131099664;
			
			// aapt resource value: 0x7f060050
			public const int ImportOverwrite = 2131099728;
			
			// aapt resource value: 0x7f060068
			public const int Info = 2131099752;
			
			// aapt resource value: 0x7f060051
			public const int InvalidImportFile = 2131099729;
			
			// aapt resource value: 0x7f06003f
			public const int InvalidKeyCode = 2131099711;
			
			// aapt resource value: 0x7f06005f
			public const int InvalidVolume = 2131099743;
			
			// aapt resource value: 0x7f060040
			public const int KeyListenError = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int KeyReceived = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int LengthTooHigh = 2131099714;
			
			// aapt resource value: 0x7f060011
			public const int MemError = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int No3DError = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int NoChanError = 2131099667;
			
			// aapt resource value: 0x7f060043
			public const int NoClientID = 2131099715;
			
			// aapt resource value: 0x7f060035
			public const int NoDevice = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int NoDeviceDriver = 2131099702;
			
			// aapt resource value: 0x7f060014
			public const int NoEaxError = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int NoFxError = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int NoHwError = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int NoPlayError = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int NotAudioError = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int NotFileError = 2131099673;
			
			// aapt resource value: 0x7f060044
			public const int PingReceived = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int PingTimeout = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int PlayError = 2131099718;
			
			// aapt resource value: 0x7f06001a
			public const int PlayingError = 2131099674;
			
			// aapt resource value: 0x7f060054
			public const int PlaylistNotFound = 2131099732;
			
			// aapt resource value: 0x7f06001b
			public const int PositionError = 2131099675;
			
			// aapt resource value: 0x7f060059
			public const int ReferencedElementNotFound = 2131099737;
			
			// aapt resource value: 0x7f060020
			public const int SetEffectError = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int SetVolumeError = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int SpeakerError = 2131099676;
			
			// aapt resource value: 0x7f060021
			public const int SpeakerNotAvailable = 2131099681;
			
			// aapt resource value: 0x7f060047
			public const int StartBroadcast = 2131099719;
			
			// aapt resource value: 0x7f060057
			public const int StartedElementNotFound = 2131099735;
			
			// aapt resource value: 0x7f060048
			public const int StopBroadcast = 2131099720;
			
			// aapt resource value: 0x7f060058
			public const int StoppedElementNotFound = 2131099736;
			
			// aapt resource value: 0x7f060022
			public const int StreamingError = 2131099682;
			
			// aapt resource value: 0x7f06005a
			public const int TagNotFound = 2131099738;
			
			// aapt resource value: 0x7f060024
			public const int TaggedMusic = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int TagsDbError = 2131099683;
			
			// aapt resource value: 0x7f060049
			public const int UDPError = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int UDPSending = 2131099722;
			
			// aapt resource value: 0x7f06001d
			public const int UnexpectedError = 2131099677;
			
			// aapt resource value: 0x7f06004b
			public const int VolumeCommandReceived = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int VolumeOutOfRange = 2131099724;
			
			// aapt resource value: 0x7f060069
			public const int Warning = 2131099753;
			
			// aapt resource value: 0x7f06004d
			public const int WrongClientLength = 2131099725;
			
			// aapt resource value: 0x7f060088
			public const int about = 2131099784;
			
			// aapt resource value: 0x7f06008e
			public const int aboutInfo = 2131099790;
			
			// aapt resource value: 0x7f060060
			public const int app_name = 2131099744;
			
			// aapt resource value: 0x7f06007e
			public const int clear = 2131099774;
			
			// aapt resource value: 0x7f06006c
			public const int connected_with = 2131099756;
			
			// aapt resource value: 0x7f06008a
			public const int connection = 2131099786;
			
			// aapt resource value: 0x7f060075
			public const int controller = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int controller_status = 2131099766;
			
			// aapt resource value: 0x7f060081
			public const int create = 2131099777;
			
			// aapt resource value: 0x7f060089
			public const int createDir = 2131099785;
			
			// aapt resource value: 0x7f06006e
			public const int directory_error = 2131099758;
			
			// aapt resource value: 0x7f06007d
			public const int filter = 2131099773;
			
			// aapt resource value: 0x7f060083
			public const int folders = 2131099779;
			
			// aapt resource value: 0x7f060066
			public const int import_error = 2131099750;
			
			// aapt resource value: 0x7f060072
			public const int importing_project = 2131099762;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060065
			public const int load_error = 2131099749;
			
			// aapt resource value: 0x7f060070
			public const int loaded_project = 2131099760;
			
			// aapt resource value: 0x7f06007f
			public const int messages = 2131099775;
			
			// aapt resource value: 0x7f060084
			public const int musicDir = 2131099780;
			
			// aapt resource value: 0x7f060061
			public const int no_ip_address = 2131099745;
			
			// aapt resource value: 0x7f060071
			public const int no_project = 2131099761;
			
			// aapt resource value: 0x7f060064
			public const int no_settings = 2131099748;
			
			// aapt resource value: 0x7f060062
			public const int no_status_info_error = 2131099746;
			
			// aapt resource value: 0x7f06006d
			public const int not_connected = 2131099757;
			
			// aapt resource value: 0x7f06008d
			public const int playerName = 2131099789;
			
			// aapt resource value: 0x7f060073
			public const int player_service = 2131099763;
			
			// aapt resource value: 0x7f060078
			public const int project = 2131099768;
			
			// aapt resource value: 0x7f060086
			public const int projectDir = 2131099782;
			
			// aapt resource value: 0x7f06007b
			public const int running = 2131099771;
			
			// aapt resource value: 0x7f060082
			public const int select = 2131099778;
			
			// aapt resource value: 0x7f06006b
			public const int service_error = 2131099755;
			
			// aapt resource value: 0x7f06006f
			public const int service_running = 2131099759;
			
			// aapt resource value: 0x7f060074
			public const int service_status = 2131099764;
			
			// aapt resource value: 0x7f060087
			public const int settings = 2131099783;
			
			// aapt resource value: 0x7f060085
			public const int soundDir = 2131099781;
			
			// aapt resource value: 0x7f060079
			public const int start = 2131099769;
			
			// aapt resource value: 0x7f060077
			public const int start_controller = 2131099767;
			
			// aapt resource value: 0x7f06007a
			public const int stop = 2131099770;
			
			// aapt resource value: 0x7f06007c
			public const int stopped = 2131099772;
			
			// aapt resource value: 0x7f060063
			public const int tags_db_error = 2131099747;
			
			// aapt resource value: 0x7f06008c
			public const int tcpPort = 2131099788;
			
			// aapt resource value: 0x7f06008b
			public const int udpPort = 2131099787;
			
			// aapt resource value: 0x7f060080
			public const int up = 2131099776;
			
			// aapt resource value: 0x7f06008f
			public const int usage = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int usageHtml = 2131099792;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int preferences = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FolderPreference = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int FolderPreference_folderType = 0;
			
			public static int[] PortPreference = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public const int PortPreference_portType = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
